#!/bin/bash
#
# Crontab monthly runner
#
# 00 4 1 * * root oai-monthly >> /var/log/oai-monthly-7.log 2>&1 &
#

SEVEN_DATA="/var/www/html/nkp/měsíční/$(date --date="$(date) -2 day" +'%Y/%m')/data"
SEVEN_BRIG_DATA="/var/www/html/nkp/NKP/$(date --date="$(date) -2 day" +'%Y/%m')/data"

# ------------------------

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

#
# "7"
#

mkdir -p "$SEVEN_DATA" 2> /dev/null
mkdir -p "$SEVEN_BRIG_DATA" 2> /dev/null

oai-7 \
	--set 'UCLA' \
	--from "$(date --date="$(date +'%Y-%m-01') -1 month" +'%Y-%m-%d 00:00:00')" \
	--until "$(date +'%Y-%m-01 00:00:00')" \
	--check \
	--notify

echo "7 done."

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

exit 0

