#!/bin/bash
#
# Crontab weekly runner
#
# 00 5 * * * root oai-weekly >> /var/log/oai-weekly.log 2>&1 &
#

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

# OAI RECENZE

oai-recenze \
	--set UCLO \
	--from "$(date --date='8 days ago' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='2 days ago' '+%Y-%m-%d 00:00:00')" \
	--check \
	--notify

# OAI CONTROL

oai-marc \
	--set UCLO \
	--from "$(date --date='8 days ago' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='2 days ago' '+%Y-%m-%d 00:00:00')" \
	--check \
	--weekly \
	--notify

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

exit 0

