#!/bin/bash
#
# Crontab weekly runner
#
# 00 5 * * * root oai-weekly >> /var/log/oai-weekly.log 2>&1 &
#

SENDER='xxx'
TARGET='xxx'
URL='xxx'

DATA_PATH='/var/www/html/weekly/data'
CSVNAME="$(date --date='8 days ago' '+%Y-%m-%d')_$(date --date='2 days ago' '+%Y-%m-%d').csv"

# ------------------------

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

# OAI RECENZE

oai-recenze \
	--set UCLA \
	--from "$(date --date='8 days ago' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='2 days ago' '+%Y-%m-%d 00:00:00')" \
	--check \
	--notify

# OAI CONTROL

oai-marc \
	--set UCLA \
	--from "$(date --date='8 days ago' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='2 days ago' '+%Y-%m-%d 00:00:00')" \
	--check

mkdir -p "$DATA_PATH" 2>/dev/null
mv -f oai-marc.csv "$DATA_PATH/$CSVNAME" 2> /dev/null

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

sendmail -r $SENDER $TARGET << EOL
From: Kontrola MARC <webmaster@vyvoj.ucl.cas.cz>
To: $TARGET
Subject: =?utf-8?B?S29udHJvbG7DrSB6cHLDoXZh?=
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8

<html>
<head><meta charset='utf-8'></head>
<body>
<br>
<div align="justify" style="width:90%">
Dobrý den,
<br><br>
Kontrolní zpráva je dostupná na adrese:
<br><br>
<a target="_blank" href="$URL">$URL</a>
<br><br>
---------------------------<br>
TATO ZPRÁVA BYLA VYGENEROVÁNA AUTOMATICKY, NEODPOVÍDEJTE NA NI.
</div>
</body>
</html>
EOL

exit 0

