#!/bin/bash
#
# Crontab hourly runner
#
# 10 * * * * root oai-hourly >> /var/log/oai-hourly.log 2>&1 &
#

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

FROM="$(date -u --date '1 hour ago' '+%Y-%m-%d %H:00:00')"
UNTIL="$(date -u '+%Y-%m-%d %H:00:00')"

# VUFIND

vufind-update --from "$FROM" --until "$UNTIL"

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

exit 0

