#!/bin/bash
#
# Crontab monthly runner
#
# 00 7 2 * * root oai-mod >> /var/log/oai-monthly.log 2>&1 &
#

#
# "5xx", "KAT", "7"
#

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

KAT_DATA="/var/www/html/kat/data/$(date --date="$(date) -2 day" +'%Y/%m')"
SEVEN_DATA="/var/www/html/seven/data/$(date --date="$(date) -2 day" +'%Y/%m')"
NKP_DATA="/var/www/html/nkp/data/$(date --date="$(date) -2 day" +'%Y/%m')"

mkdir -p "$KAT" 2> /dev/null
mkdir -p "$SEVEN_DATA" 2> /dev/null
mkdir -p "$NKP_DATA" 2> /dev/null

oai-mod \
	--set 'UCLA' \
	--from "$(date --date='yesterday' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='today' '+%Y-%m-%d 00:00:00')" \

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

exit 0

