#!/bin/bash
#
# Crontab weekly runner
#
# 00 5 * * * root oai-weekly >> /var/log/oai-weekly.log 2>&1 &
#

EMAIL='xxx'
URL='xxx'

DATA_PATH='/var/www/html/weekly/data'
CSVNAME="$(date --date='8 days ago' '+%Y-%m-%d')_$(date --date='2 days ago' '+%Y-%m-%d').csv"

# ------------------------

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

# OAI RECENZE

oai-recenze \
	--set UCLA \
	--from "$(date --date='8 days ago' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='2 days ago' '+%Y-%m-%d 00:00:00')" \
	--check \
	--notify

# OAI CONTROL

oai-marc \
	--set UCLA \
	--from "$(date --date='8 days ago' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='2 days ago' '+%Y-%m-%d 00:00:00')" \
	--check

mkdir -p "$DATA_PATH" 2>/dev/null
mv -f oai-marc.csv "$DATA_PATH/$CSVNAME" 2> /dev/null

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

cat << EOF | mail -s 'Kontrolní zpráva' $EMAIL
Dobrý den,

Kontrolní zpráva je dostupná na adrese:

$URL

---------------------------
TATO ZPRÁVA BYLA VYGENEROVÁNA AUTOMATICKY,
NEODPOVÍDEJTE NA NI.
EOF

exit 0

