<h2>Export</h2>

<div>
<label for="format" class="control-label"><?=$this->transEsc('Format')?>:</label>
</div>
<!--form type="post" action="/export" data-lightbox-ignore>-->
<form method="post" action="/export" data-lightbox-ignore>
	<select name="format" id="format">
		<option value="txt">TXT</option>
		<option value="json">JSON</option>
		<option value="marcxml">MARCXML</option>
		<option value="marc21">MARC21</option>
		<option value="pdf">PDF</option>
		<option value="docx">DOCX</option>
	</select>
	<input class="export btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('Export')?>"/>
</form>
</div>
<div class="modal-body">
<a target="_blank" href="/export">EXPORT</a></br>
<a href="https://clb.ucl.cas.cz" data-lightbox-href="https://google.com">LINK1</a></br>
<a href="/export" data-lightbox-ignore>LINK2</a></br>
</div>
