<h2><?=$this->transEsc('Export Favorites')?></h2>

<?php

print_r($this->exportOptions);

?>

<form method="post" action="/export" title="<?=$this->transEscAttr('Export Items')?>">
	<div class="form-group">
	<label for="format" class="control-label"><?=$this->transEsc('Format')?>:</label>
	<select name="format" id="format" class="form-control">

<?php

	$firstOption = null;

	#foreach ($this->exportOptions as $exportOption) {
	#	if ($firstOption == null) { $firstOption = $exportOption; }
	#		echo '<option value="' . $this->escapeHtmlAttr($exportOption) . '">'
	#		. $this->transEsc($this->export()->getLabelForFormat($exportOption)) . '</option>';
	#}
?>

	</select>
	</div>
	<div class="form-group">
	<input class="export btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('Export')?>"<?php if($this->export()->needsRedirect($firstOption)): ?> data-lightbox-ignore<?php endif; ?>/>
	</div>
</form>

