<h2>Export</h2>

<form class="form-cart-export" method="post" action="/export?<?=$_SERVER['QUERY_STRING'];?>" name="exportForm" title="<?=$this->transEscAttr('Export Items')?>">
	<div class="form-group">
		<label for="format" class="control-label"><?=$this->transEsc('Format')?>:</label>
		<select name="format" id="format" name="type" class="form-control">
	<!--		<option value="txt">TXT</option>
			<option value="json">JSON</option>
			<option value="marc21">MARC21</option> -->
			<option value="marcxml">MARCXML</option>
			<option value="docx">DOCX</option>
			<option value="pdf">PDF</option>
		</select>
	</div>
	<div class="form-group">
		<input class="export btn btn-primary" type="submit" value="<?=$this->transEscAttr('Save')?>" data-lightbox-ignore/>
	</div>
</form>

