<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?php
    $QRCode = $this->record($this->driver)->getQRCode("core");
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
    $cover = $coverDetails['html'];
    $preview = $this->record($this->driver)->getPreviews();
  ?>
  <?php if ($QRCode || $cover || $preview): ?>
    <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php if($cover): ?>
        <?=$cover?>
      <?php endif; ?>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <?php endif; ?>

      <?php // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <?php if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <div class="media-body">

    <h3 property="name"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h3>

    <?php $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <?php if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <?php if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */ ?>
    <?php
      $formatter = $this->recordDataFormatter();
      $coreFields = $formatter->getData($driver, $formatter->getDefaults('core'));
    ?>
    <?php if (!empty($coreFields)): ?>
      <table class="table table-striped">
        <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
        <?php foreach ($coreFields as $current): ?>
 <!--         <tr><th><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr> -->
        <?php endforeach; ?>
	
<?php

$responsibility = $this->driver->getResponsibility();
        if (!empty($responsibility)) {
		echo "<tr><th>" . $this->transEsc("Statement of Responsibility") . ":</th><td>" . $responsibility . "</td></tr>";
	}
$BookChapterInfo = "";
$downArray = ["Subjects", "Online Access", "Tags"];
foreach ($coreFields as $current) {
	if (!in_array($current['label'], $downArray)) {
#print_r($current);

		if (($current['label'] == "Format") && (strpos($current['value'], "knihy") == true)) { 
			$BookChapterInfo = $this->driver->getBookChapterInfo();
#			print_r($BookChapterInfo);
		}
// TODO find out why it doeasnt work with Main
		if ((strpos($current['label'], "Author"))) {
			$withoutRoleArray = explode("</a>", $current['value']);
			$itemCount = count($withoutRoleArray);
			if ($itemCount > 0) { 
				foreach ( $withoutRoleArray as $item) { 
				        $lastWordAr = explode(" ", $item);
				        $lastWord = array_pop($lastWordAr);
				        if (preg_match_all( "/[0-9]/", $lastWord)>3) {
		        			$current['value'] = str_replace($lastWord, '',  $current['value']);
					}
				}
			}
		}
                if ($current['label'] == "Language") {
                        $languageArray = explode("<br />", $current['value']);
                        foreach ( $languageArray as $item) {
                                $current['value'] = str_replace($item, $this->transEsc($item),  $current['value']);
                        }
                }

		echo "<tr><th>" . $this->transEsc($current['label']) . ":</th><td>" . $current['value'] . "</td></tr>";
	}
}

#	} else {
#		echo "a " . $current['label'];
#	}
#}
#print_r($coreFields[1]['value']);
 ?>

     <?php 
	if (empty($BookChapterInfo)) {
		$misto = $this->driver->getMisto(); 
	} else {
		$misto = $BookChapterInfo;
	}
	if (!empty($misto)): 
    ?>
    <tr>
      <th><?=$this->transEsc('In')?>: </th>
       <td property="misto"><?php echo $misto; ?></td>
     </tr>
    <?php endif; ?>

    <?php
        $zanr = $this->driver->getZanr();
        if (!empty($zanr)):
    ?>
    <tr>
      <th><?=$this->transEsc('Form/Genre')?>: </th>
       <td property="genre"><?php echo $zanr; ?></td>
     </tr>
    <?php endif; ?>


    <?php
        $odkazovaneDilo = $this->driver->getOdkazovaneDilo();
        if (!empty($odkazovaneDilo)):
    ?>
    <tr>
      <th><?=$this->transEsc('Referred work')?>: </th>
       <td property="link"><?php echo $odkazovaneDilo; ?></td>
     </tr>
    <?php endif; ?>
<?php
foreach ($coreFields as $current) {
        if (in_array($current['label'], $downArray)) {
                echo "<tr><th>" . $this->transEsc($current['label']) . ":</th><td>" . $current['value'] . "</td></tr>";
        }

}
?>

    <?php
        $aktualniexcerpce = $this->driver->getActualExcerption();
        if (!empty($aktualniexcerpce)):
    ?>
    <tr>
      <th><?=$this->transEsc('Actual Excerption')?>: </th>
       <td property="link"><?php echo $aktualniexcerpce; ?></td>
     </tr>
    <?php endif; ?>

    <?php
        $ukoncenaexcerpce = $this->driver->getFinishedExcerption();
        if (!empty($ukoncenaexcerpce)):
    ?>
    <tr>
      <th><?=$this->transEsc('Finished Excerption')?>: </th>
       <td property="link"><?php echo $ukoncenaexcerpce; ?></td>
     </tr>
    <?php endif; ?>



    <?php
        $citace = $this->driver->getCitation();
        if (!empty($citace)):
    ?>
    <tr>
      <th><?=$this->transEsc('Citation')?>: </th>
       <td property="link"><?php echo $citace; ?></td>
     </tr>
    <?php endif; ?>

      </table>
    <?php endif; ?>
    <?php /* End Main Details */ ?>
  </div>
</div>
