<div class="info-line" property="keywords">
<?php if (isset($data['resource'])): ?>
	<?php $i=0; foreach ($data['resource'] as $resource): ?>
		<a title="<?=$this->escapeHtmlAttr($resource)?>" href="<?=$this->record($this->driver)->getLink('article', $resource)?>" rel="nofollow"><?=trim($this->escapeHtml($resource))?></a>
		<?=' -- '?>
	<?php endforeach; ?>
<?php endif; ?>
<?php if (isset($data['sub'])): ?>
	<?php foreach ($data['sub'] as $subfields): ?>
		<?php foreach ($subfields as $subfield => $value): ?>
			<?php if ($subfield == 'x'): ?>
				<a title="<?=$this->escapeHtmlAttr($value)?>" href="<?=$this->record($this->driver)->getLink('isn', $value)?>" rel="nofollow"><?=trim($this->escapeHtml($value))?></a>
				<?=' -- '?>
			<?php elseif ($subfield == 'z'): ?>
				<a title="<?=$this->escapeHtmlAttr($value)?>" href="<?=$this->record($this->driver)->getLink('isn', $value)?>" rel="nofollow"><?=trim($this->escapeHtml($value))?></a>
			<?php else: ?>
				<?php echo $value . ' -- ' ; ?>
			<?php endif; ?>
		<?php endforeach; ?>
	<?php endforeach; ?>
<?php endif; ?>
<?php if (isset($data['related'])): ?>
	<?php foreach ($data['related'] as $related): ?>
		<?=$related;?>
	<?php endforeach; ?>
<?php endif; ?>
</div>
