<div class="relations-line" property="keywords">
<?php foreach ($data as $relations): ?>
	<?php $i=0; foreach ($relations as $direction => $record): ?>
		<?php if ($direction == 'UP'): ?>
			<a title="<?=$this->transEsc('relations_up')?>" href="<?=$this->url('record') . $record?>" rel="nofollow"><?=$this->transEsc('relations_up')?></a></br>
		<?php endif; ?>
		<?php if ($direction == 'DOWN'): ?>
			<a title="<?=$this->transEsc('relations_down')?>" href="<?=$this->url('record') . $record?>" rel="nofollow"><?=$this->transEsc('relations_down')?></a></br>
		<?php endif; ?>
		<?php if ($direction == 'PAR'): ?>
			<a title="<?=$this->transEsc('relations_par')?>" href="<?=$this->url('record') . $record?>" rel="nofollow"><?=$this->transEsc('relations_par')?></a></br>
		<?php endif; ?>
	<?php endforeach; ?>
<?php endforeach; ?>
</div>
