<?php if (isset($data['detail'])): ?>
	<?php foreach ($data['detail'] as $detail): ?>
		<a title="<?=$this->escapeHtmlAttr($link)?>" href="<?=$this->record($this->driver)->getLink('related', $detail)?>" rel="nofollow"><?=trim($this->escapeHtml($detail))?></a><br>
	<?php endforeach; ?>
<?php endif; ?>
<?php if (isset($data['sub'])): ?>
	<?php foreach ($data['sub'] as $subfields): ?>
		<?php $author = trim((isset($subfields['a']) ? $subfields['a'] : '') . '. ' . (isset($subfields['t']) ? $subfields['t'] : ''), ' .'); ?>
		<?php if (!empty($author)): ?>
			<a title="<?=$this->escapeHtmlAttr($author)?>" href="<?=$this->record($this->driver)->getLink('related', $author)?>" rel="nofollow"><?=trim($this->escapeHtml($author))?></a><?=' -- '?>
		<?php endif; ?>
		<?php foreach ($subfields as $subfield => $value): ?>
			<?php if ($subfield == '4'): ?>
				<?php echo '[' . $value . ']' ; ?>
			<?php elseif (! in_array($subfield, array('a','t'))): ?>
				<?php echo $value . ' -- ' ; ?>
			<?php endif; ?>
		<?php endforeach; ?>
		<br>
	<?php endforeach; ?>
<?php endif; ?>
