<div class="info-line" property="keywords">
<?php foreach ($data as $info): ?>
	<?php $i=0; foreach ($info as $label => $value): ?>
		<?= ($i++ == 0) ? '' : ' -- '; ?>
		<?php if ($label == 'title'): ?>
			<a title="<?=$this->escapeHtmlAttr($value)?>" href="<?=$this->record($this->driver)->getLink('title', $value)?>" rel="nofollow"><?=trim($this->escapeHtml($value))?></a>
		<?php endif; ?>
		<?php if ($label == 'isbn'): ?>
			<?php $j=0; foreach ($value as $isn): ?>
				<?= ($j++ == 0) ? '' : ' -- '; ?>
				<a title="<?=$this->escapeHtmlAttr($isn)?>" href="<?=$this->record($this->driver)->getLink('isn', $isn)?>" rel="nofollow"><?=trim($this->escapeHtml($isn))?></a>
			<?php endforeach; ?>
		<?php endif; ?>
		<?php if ($label == 'issn'): ?>
			<a title="<?=$this->escapeHtmlAttr($value)?>" href="<?=$this->record($this->driver)->getLink('isn', $value)?>" rel="nofollow"><?=trim($this->escapeHtml($value))?></a>
		<?php endif; ?>
		<?php if ($label == 'related'): ?>
			<?php echo $value; ?>
		<?php endif; ?>
	<?php endforeach; ?>
<?php endforeach; ?>
</div>
