<?php foreach ($data as $field): ?>
  <span property="publisher" typeof="Organization">
  <?php $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
    <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
  <?php endif; ?>
  <?php $pubName = $field->getName(); $pubDate = $field->getDate(); if (!empty($pubName)): ?>
     <?php if (!empty($pubDate)): ?>
        <a property="name" href="<?=$this->record($this->driver)->getLink('publisher', $pubName)?>"><?=$this->escapeHtml($pubName)?></a>,
     <?php else: ?>
        <a property="name" href="<?=$this->record($this->driver)->getLink('publisher', $pubName)?>"><?=$this->escapeHtml($pubName)?></a>
     <?php endif; ?>
  <?php endif; ?>
  </span>
  <?php if (!empty($pubDate)): ?>
        <span property="datePublished"><?=$this->escapeHtml($pubDate)?></span>
  <?php endif; ?>
  <br/>
<?php endforeach; ?>
