
OriginalName:
  DismaxFields:
    - original_txt_mv
  DismaxHandler: edismax

CypherSignature:
  DismaxFields:
    - cypher_txt_mv
  DismaxHandler: edismax

SysNo:
  DismaxFields:
    - id
    - id2_str
  DismaxHandler: edismax

ConspectGroup:
  DismaxFields:
    - conspect_group_str_mv
  DismaxHandler: edismax

ConspectResource:
  DismaxFields:
    - more_info_str_mv
  DismaxHandler: edismax

ActualExcerption:
  DismaxFields:
    - actual_excerption_txt_mv
  DismaxHandler: edismax

FinishedExcerption:
  DismaxFields:
    - finished_excerption_txt_mv
  DismaxHandler: edismax

ArticleResource:
  DismaxFields:
    - article_resource_txt_mv
  DismaxHandler: edismax

AuthorityResource:
  DismaxFields:
    - authority_search_str_mv
  DismaxHandler: edismax

Yearstr:
  DismaxFields:
    - date_txt_mv
  DismaxHandler: edismax

LinkedResource:
  DismaxFields:
    - related_doc_search_txt_mv
  DismaxHandler: edismax
  
Subject:
  DismaxFields:
    - topic_unstemmed^150
    - topic_search_str_mv^100
    - geographic^50
    - era
  DismaxHandler: edismax

PublishPlaceStr:
  DismaxFields:
    - publication_place_txt_mv
  DismaxHandler: edismax

AuthorTopic:
  DismaxFields:
    - topic_person_txt_mv
  DismaxHandler: edismax

RetrobiOCR:
  DismaxFields:
    - retrobitxt_txt_mv
  DismaxHandler: edismax

recordcreation:
  DismaxFields:
    - record_creation_str_mv
  DismaxHandler: edismax

recordchange:
  DismaxFields:
    - record_change_str_mv
  DismaxHandler: edismax

recordprocessor:
  DismaxFields:
    - processor_txt_mv
  DismaxHandler: edismax

authorbirthyear:
  DismaxFields:
    - author_birth_year_str_mv
  DismaxHandler: edismax

linkedpersonbirthyear:
  DismaxFields:
    - linked_person_birth_year_str_mv
  DismaxHandler: edismax


# Fields for exact matches originating from alphabetic browse                                                                                                                          
 
SourceBrowse:
  QueryFields:
    source_browse: 
      - [onephrase, ~]
                                                                                                                                                                                     
