#!/usr/bin/python
# -*- coding: utf-8 -*-

# INCLUDE -------------------

from __future__ import print_function

import StringIO,requests,lxml.html,time,sys,os,re

from pymarc import marcxml,Field,MARCWriter,MARCReader, XMLWriter
from pymarc.record import Record

# VAR -------------------

IN='651.txt'
DATA='ucla.xml'
OUT='651.aleph'

# crate map from source

MAP={}

with open(IN, 'r') as src:
	for line in src:
		DATA=[]
		orig,raw = line.strip().split(';;;')
		if not raw: break
		for R in raw.split('|')[1:]:
			DATA.append(R[0])
			DATA.append(R[1:].strip())
		MAP[orig] = DATA


# loop over data and write all 651 in aleph format

aleph = open(OUT, 'w')

def validate(record):

	metadata = record

	IDENT = metadata['001'].value()

	for F in metadata.getfields('651'):
		if F['a'] in MAP:

		else:
			SUB=''
			for i in range(0, len(F.subfields)/2):
				SUB+='$$' + F.subfields[i*2] + F.subfields[i*2+1]
			aleph.write(str(IDENT) + ' 651' + F.indicator1 + F.indicator2 + ' L ' + SUB + '\n')

# MAIN ------------------------------------------------------

marcxml.map_xml(validate, DATA)

aleph.close()

# EXIT -------------------

sys.exit(0)

