#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Aleph MARC 773 -> 856 convertor
#
# Tvar
#                                              R     Y    C             S
# 001321647 7730  L $$tTvar$$x0862-657X$$gRoč. 17, 2006, č. 3, 9. 2., s. 22$$q17:3<22$$920060209
#                                              R  Y   C S
# http://archiv.ucl.cas.cz/index.php?path=Tvar/2.1992/1/1.png
#    ID                  URL      
# XXXXXXXXX 85641 L $$ uYYY $$y Digitální archiv časopisů $$ 4 N
#

from __future__ import print_function

import StringIO,requests,sys,os,re

from oaipmh.client import Client
from oaipmh.metadata import MetadataRegistry
from pymarc import marcxml,Field
from lxml.etree import tostring

# VAR ----------------------------------

IN='data.txt'
OUT='773to856_TVAR.bib'
LOG='773to856_TVAR.log'

PREFIX='http://archiv.ucl.cas.cz/index.php?path=Tvar/'
URL='https://aleph.lib.cas.cz/OAI'

TOTAL=0
MATCH=0
BROKEN=0
MAN=0

# DEF ----------------------------------

def MarcXML(xml):
	handler = marcxml.XmlHandler()
	marcxml.parse_xml(StringIO.StringIO(tostring(xml, encoding='utf-8')), handler)
	return handler.records[0]

def url_response(url,i,log):
	try:
		if re.match('.*\.png', url):
			req = session.get(url)
			if req.status_code == 200:
				if 'Tisk' in req.text:
					return 1
		if re.match('.*\.pdf', url):
			req = session.get(url)
			if req.status_code == 200:
				if len(req.content) > 0: # Check if valid PDF file
					if '\x25\x50\x44\x46' in req.content:
						return 1
	except:
		log.write(i + ' URL check failed.\n')

def write_record(bib,url,i,log):
	try:
		#oai:aleph22.lib.cas.cz:KNA01-001394011
		record,header,about='','',''
		header, record, about = oai.getRecord(metadataPrefix='marc21', identifier='oai:aleph22.lib.cas.cz:KNA01-' + i)
		if record:
			if '856' in record:
				log.write(i + ' Has 856.\n')
			else:
				# XXXXXXXXX 85641 L $$ uYYY $$y Digitální archiv časopisů $$ 4 N
				bib.write(i + ' 85641 L $$u' + url + u'$$yDigitální archiv časopisů'.encode('utf-8') + '$$4N\n')
		else:
			log.write(i + ' No record.\n')
	except:
		log.write(i + ' Write failed.\n')

def convert_q(q,g,i,out,log):
	R = re.sub('(\d+):(\d+|\d+\/\d+)<\[?\d+\]?', '\\1', q).strip()
	C = re.sub('\d+:(\d+|\d+\/\d+)<\[?\d+\]?', '\\1', q).strip().split('/')
	S = re.sub('\d+:(\d+|\d+\/\d+)<\[?(\d+)\]?', '\\2', q).strip()

	if R in [str(r) for r in range(1, 19)]:
		if R in ('1', '2', '3', '4', '5', '6', '7'):
			R = R + '.' + str(int(R) + 1989)
		else:
			R = str(int(R) + 1989)

		if R == '2005':
			if len(C) == 1:
				URL = PREFIX + R + '/' + C[0].strip() + '/' + S + '.pdf'
			if len(C) == 2:
				URL = PREFIX + R + '/' + C[0].strip() + '-' + C[1].strip() + '/' + S + '.pdf'
		elif R in ('2006', '2007'):
			if len(C) == 1:
				URL = PREFIX + R + '/' + C[0].strip() + '.pdf'
			if len(C) == 2:
				URL = PREFIX + R + '/' + C[0].strip() + '-' + C[1].strip() + '.pdf'
		else:
			if len(C) == 1:
				URL = PREFIX + R + '/' + C[0].strip() + '/' + S + '.png'
			if len(C) == 2:
				URL = PREFIX + R + '/' + C[0].strip() + '-' + C[1].strip() + '/' + S + '.png'

		if url_response(URL,i,log):
			write_record(out,URL,i,log)
		else:
			log.write(i + ' BAD ' + URL + ' => ' + g)
	else:
		log.write(i + ' YEAR ' + g)

def convert_broken(g,i,out,log):
	Y = re.sub('^Roč\. \d+, (\d+), .*$', '\\1', g).strip()
	R = re.sub('^Roč\. (\d+), .*$', '\\1', g).strip()
	C = re.sub('^Roč\. \d+, \d+, č\. (\d+), .*$', '\\1', g).strip()
	S = re.sub('^.*, s\. (\d+|\d+-\d+)$', '\\1', g).split('-')[0].strip()

	if R in [str(r) for r in range(1, 19)]:
		if R in ('1', '2', '3', '4', '5', '6', '7'):
			R = R + '.' + str(int(R) + 1989)
		else:
			R = str(int(R) + 1989)

		if R == '2005':
			if len(C) == 1:
				URL = PREFIX + R + '/' + C[0].strip() + '/' + S + '.pdf'
			if len(C) == 2:
				URL = PREFIX + R + '/' + C[0].strip() + '-' + C[1].strip() + '/' + S + '.pdf'
		elif R in ('2006', '2007'):
			if len(C) == 1:
				URL = PREFIX + R + '/' + C[0].strip() + '.pdf'
			if len(C) == 2:
				URL = PREFIX + R + '/' + C[0].strip() + '-' + C[1].strip() + '.pdf'
		else:
			if len(C) == 1:
				URL = PREFIX + R + '/' + C[0].strip() + '/' + S + '.png'
			if len(C) == 2:
				URL = PREFIX + R + '/' + C[0].strip() + '-' + C[1].strip() + '/' + S + '.png'

		if url_response(URL,i,log):
			write_record(out,URL,i,log)
		else:
			log.write(i + ' BAD ' + URL + ' => ' + g)
	else:
		log.write(i + ' YEAR ' + g)

# INIT ----------------------------------

registry = MetadataRegistry()

registry.registerReader('marc21', MarcXML)

oai = Client(URL, registry)

session = requests.Session()

# MAIN ----------------------------------

in_file = open(IN, 'r')
out_file = open(OUT, 'w')
log_file = open(LOG, 'w', 0)

for LINE in in_file:
	if re.match('.*L \$\$tTvar\$\$x0862-657X\$\$.*', LINE):
		TOTAL+=1
		ID = LINE[:9]
		G = re.sub('^.*\$\$g(.*)\$\$q.*$', '\\1', LINE)
		Q = re.sub('^.*\$\$q(.*)\$\$.*$', '\\1', LINE)
		#Q
		if re.match('\d+:(\d+|\d+\/\d+)<\[?\d+\]?', Q):
			MATCH+=1
			convert_q(Q,G,ID,out_file,log_file)
			continue
		# BROKEN
		if re.match('^Roč\. \d+, \d+, č\. \d+, \d+\. \d+\., s\. (\d+|\d+-\d+)$', G):
			BROKEN+=1
		#	convert_broken(G,ID,out_file,log_file)
			continue
		#MANUAL
		MAN+=1
		#print(LINE.strip())
		log_file.write(ID + ' MANUAL ' + G)

print('TOTAL: ' + str(TOTAL))
print('MATCH: ' + str(MATCH))
print('BROKEN: ' + str(BROKEN))
print('MAN: ' + str(MAN))

in_file.close()
out_file.close()
log_file.close()

