#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Aleph MARC 773 -> 856 convertor
#
# Literarni noviny
#                                                        R       Y    C            S
# 001965093 7730  L $$tLiterární noviny$$x1804-820X$$gRoč. 20, 1951, č. 5, 5. 5., s. 70$$q20:5<70$$919510505
#                                              R  Y   C S
# http://archiv.ucl.cas.cz/index.php?path=LitN/2.1928/1/1.png
#    ID                  URL      
# XXXXXXXXX 85641 L $$ uYYY $$y Digitální archiv časopisů $$ 4 N
#

from __future__ import print_function

import StringIO,requests,sys,os,re

from oaipmh.client import Client
from oaipmh.metadata import MetadataRegistry
from pymarc import marcxml,Field,record_to_xml_node
import xml.etree.ElementTree as ET
from lxml.etree import tostring

# VAR ----------------------------------

IN='data.txt'
OUT='773to856.bib'
XML='773to856.xml'
LOG='773to856_LITN.log'

PREFIX='http://archiv.ucl.cas.cz/index.php?path=LitN/'
URL='https://aleph.lib.cas.cz/OAI'

TOTAL=0
MATCH=0
MAN=0

# DEF ----------------------------------

def MarcXML(xml):
	handler = marcxml.XmlHandler()
	marcxml.parse_xml(StringIO.StringIO(tostring(xml, encoding='utf-8')), handler)
	return handler.records[0]

def url_response(url,i,log):
	try:
		req = session.get(url)
		if req.status_code == 200:
			if 'Tisk' in req.text:
				return 1
	except:
		log.write(i + ' URL check failed.\n')

def write_record(bib,url,i,log):
	try:
		#oai:aleph22.lib.cas.cz:KNA01-001394011
		record,header,about='','',''
		header, record, about = oai.getRecord(metadataPrefix='marc21', identifier='oai:aleph22.lib.cas.cz:KNA01-' + i)
		if record:
			if '856' in record:
				log.write(i +' Has 856.\n')
			else:
				# XXXXXXXXX 85641 L $$ uYYY $$y Digitální archiv časopisů $$ 4 N
				# ALEPH
				#bib.write(i + ' 85641 L $$u' + url + u'$$yDigitální archiv časopisů'.encode('utf-8') + '$$4N\n')
				# XML
				xml_file.write(ET.tostring(record_to_xml_node(record), encoding='utf-8'))
				# MARC
				field = Field(
					tag = '856',
					indicators = ['4','1'],
					subfields = ['u', url, 'y', u'Digitální archiv časopisů', '4', 'N']
				)
				record.add_ordered_field(field)
				bib.write(record.__str__())
				bib.write('\n')
		else:
			log.write(i + ' No record.\n')
	except:
		log.write(i + ' Write failed.\n')

def convert_q(q,g,i,out,log):
	R = re.sub('(\d+):(\d+|\d+\/\d+)<\d+', '\\1', q).strip()
	C = re.sub('\d+:(\d+|\d+\/\d+)<\d+', '\\1', q).strip().split('/')
	S = re.sub('\d+:(\d+|\d+\/\d+)<(\d+)', '\\2', q).strip()

	if R in ('1', '15', '16', '17', '18', '19', '20'):

		if R == '1': R = '1.1927'
		if R == '15': R = '15.1946'
		if R == '16': R = '16.1947'
		if R == '17': R = '17.1948'
		if R == '18': R = '18.1949'
		if R == '19': R = '1950'
		if R == '20': R = '1951'

		if len(C) == 1:
			URL = PREFIX + R + '/' + C[0].strip() + '/' + S + '.png'
		if len(C) == 2:
			URL = PREFIX + R + '/' + C[0].strip() + '-' + C[1].strip() + '/' + S + '.png'

		if url_response(URL,i,log):
			write_record(out,URL,i,log)
		else:
			log.write(i + ' BAD ' + URL + ' => ' + g)
	else:
		log.write(i + ' YEAR ' + g)

# INIT ----------------------------------

registry = MetadataRegistry()

registry.registerReader('marc21', MarcXML)

oai = Client(URL, registry)

session = requests.Session()

# MAIN ----------------------------------

in_file = open(IN, 'r')
out_file = open(OUT, 'a', 0)
xml_file = open(XML, 'a', 0)
log_file = open(LOG, 'w', 0)

for LINE in in_file:
	if re.match('.*L \$\$tLiterární noviny\$\$x1804-820X\$\$.*', LINE):
		TOTAL+=1
		ID = LINE[:9]
		G = re.sub('^.*\$\$g(.*)\$\$q.*$', '\\1', LINE)
		Q = re.sub('^.*\$\$q(.*)\$\$.*$', '\\1', LINE)
		#Q
		if re.match('\d+:(\d+|\d+\/\d+)<\d+', Q):
			MATCH+=1
			convert_q(Q,G,ID,out_file,log_file)
			continue
		#MANUAL
		MAN+=1
		#print(LINE.strip())
		log_file.write(ID + ' MANUAL ' + G)

print('TOTAL: ' + str(TOTAL))
print('MATCH: ' + str(MATCH))
print('MAN: ' + str(MAN))

in_file.close()
out_file.close()
xml_file.close()
log_file.close()

