#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Aleph MARC 773 -> 856 convertor
#
# Kultura
#                                                      Y     C              S
# 001116128 7730  L $$tKultura$$x0452-7984$$gRoč. 3, 1959, č. 38, 24. 9., s. 5$$q3:38$$919590924 
#                                              P   Y  C S
# http://archiv.ucl.cas.cz/index.php?path=Kult/2.1958/1/1.png
#    ID                  URL      
# XXXXXXXXX 85641 L $$ uYYY $$y Digitální archiv časopisů $$ 4 N
#

from __future__ import print_function

import StringIO,requests,sys,os,re

from oaipmh.client import Client
from oaipmh.metadata import MetadataRegistry
from pymarc import marcxml,Field
from lxml.etree import tostring

# VAR ----------------------------------

IN='data.txt'
OUT='773to856_KULT.bib'
LOG='773to856_KULT.log'

PREFIX='http://archiv.ucl.cas.cz/index.php?path=Kult/'
URL='https://aleph.lib.cas.cz/OAI'

TOTAL=0
MATCH=0
BROKEN=0
MAN=0

# DEF ----------------------------------

def MarcXML(xml):
	handler = marcxml.XmlHandler()
	marcxml.parse_xml(StringIO.StringIO(tostring(xml, encoding='utf-8')), handler)
	return handler.records[0]

def url_response(url,i,log):
	try:
		req = session.get(url)
		if req.status_code == 200:
			if 'Tisk' in req.text:
				return 1
	except:
		log.write(i + ' URL check failed.\n')

def write_record(bib,url,i,log):
	try:
		#oai:aleph22.lib.cas.cz:KNA01-001394011
		record,header,about='','',''
		header, record, about = oai.getRecord(metadataPrefix='marc21', identifier='oai:aleph22.lib.cas.cz:KNA01-' + i)
		if record:
			if '856' in record:
				log.write(i + ' Has 856.')
			else:
				# XXXXXXXXX 85642 L $$ uYYY $$y Digitální archiv časopisů $$ 4 N
				field = Field(
					tag = '856',
					indicators = ['4','1'],
					subfields = ['u', url, 'y', u'Digitální archiv časopisů', '4', 'N']
				)
				record.add_ordered_field(field)
				bib.write(record.__str__())
				bib.write('\n')
		else:
			log.write(i + ' No record.\n')
	except:
		log.write(i + ' Write failed.\n')

def convert_q(q,g,i,out,log):
	R = re.sub('\[?(\d+)\]?:(\d+|\d+\/\d+)<\d+', '\\1', q).strip()
	C = re.sub('\[?\d+\]?:(\d+|\d+\/\d+)<\d+', '\\1',q).strip().split('/')
	S = re.sub('\[?\d+\]?:(\d+|\d+\/\d+)<(\d+)', '\\2',q).strip()

	if R in ('1','2','3','4','5','6'):
		if R == '1': R = '1957'
		if R == '2': R = '2.1958'
		if R == '3': R = '3.1959'
		if R == '4': R = '4.1960'
		if R == '5': R = '5.1961'
		if R == '6': R = '6.1962'

		if len(C) == 1:
			URL = PREFIX + R + '/' + C[0].strip() + '/' + S + '.png'
		if len(C) == 2:
			URL = PREFIX + R + '/' + C[0].strip() + '-' + C[1].strip() + '/' + S + '.png'

		if url_response(URL,i,log):
			write_record(out,URL,i,log)
		else:
			log.write(i + ' BAD ' + URL + ' => ' + g)
	else:
		log.write(i + ' YEAR ' + g)

def convert_broken(g,i,out,log):
	R = re.sub('^Roč\. (\d+|\[\d+\]), .*$', '\\1', g).strip().replace('[','').replace(']','')
	C = re.sub('^Roč\. (\d+|\[\d+\]), \d+, č\. (\d+|\d+\/\d+), .*$', '\\2' , g).strip().split('/')
	s_part = re.sub('^.*, s\. (\d+|\d+-\d+|\d+, \d+|\d+ a \d+)$', '\\1' , g)
	S = s_part.split('-')[0].split(', ')[0].split(' a ')[0].strip()

	if R in ('1','2','3','4','5','6'):
		if R == '1': R = '1957'
		if R == '2': R = '2.1958'
		if R == '3': R = '3.1959'
		if R == '4': R = '4.1960'
		if R == '5': R = '5.1961'
		if R == '6': R = '6.1962'

		if len(C) == 1:
			URL = PREFIX + R + '/' + C[0].strip() + '/' + S + '.png'
		if len(C) == 2:
			URL = PREFIX + R + '/' + C[0].strip() + '-' + C[1].strip() + '/' + S + '.png'

		if url_response(URL,i,log):
			write_record(out,URL,i,log)
		else:
			log.write(i + ' BAD ' + URL + ' => ' + g)
	else:
		log.write(i + ' YEAR ' + g)

# INIT ----------------------------------

registry = MetadataRegistry()

registry.registerReader('marc21', MarcXML)

oai = Client(URL, registry)

session = requests.Session()

# MAIN ----------------------------------

in_file = open(IN, 'r')
out_file = open(OUT, 'w')
log_file = open(LOG, 'w', 0)

for LINE in in_file:
	if re.match('.*L \$\$tKultura\$\$.*', LINE):
		TOTAL+=1
		ID = LINE[:9]
		G = re.sub('^.*\$\$g(.*)\$\$q.*$', '\\1', LINE)
		Q = re.sub('^.*\$\$q(.*)\$\$.*$', '\\1', LINE)

		# Q
		if re.match('\[?\d+\]?:(\d+|\d+\/\d+)<\d+', Q):
			MATCH+=1
			convert_q(Q,G,ID,out_file,log_file)
			continue
		# BROKEN
		if re.match('^Roč\. (\d+|\[\d+\]), \d+, č\. (\d+|\d+\/\d+), \d+\. \d+\., s\. (\d+|\d+-\d+|\d+, \d+|\d+ a \d+)$', G):
			BROKEN+=1
			convert_broken(G,ID,out_file,log_file)
			continue
		# MANUAL
		MAN+=1
		log_file.write(ID + ' MANUAL ' + G)
		#print(LINE.strip())

print('TOTAL: ' + str(TOTAL))
print('MATCH: ' + str(MATCH))
print('BROKEN: ' + str(BROKEN))
print('MAN: ' + str(MAN))

in_file.close()
out_file.close()
log_file.close()

