<?php

#Sysno - zarovnat vpravo do rohu
#100 a, b, c - ideálně tvar PŘÍJMENÍ, jméno
#245 - lze vzít bez dalších úprav tak, jak je
#260/264 - opět lze vzít bez dalších úprav (bude jen u knih)
#490 -  opět lze vzít bez dalších úprav (bude jen u knih)
#In: 773t. 773g (bude jen u článků a částí knih)
##[520a.]
#-> všechna pole 6XX (bez 655; za sebe, oddělená středníkem)
#-> všechna pole 787 (každé na nový řádek)

$marc = $this->driver->tryMethod('getMarcReader');

echo '<!doctype html><html lang="cs">'
	. '<head>'
	. '<meta charset="utf-8">'
	. '<meta name="viewport" content="width=device-width, initial-scale=1">'
	. '<title>ČLB - Kartičky</title>'
	. '</head>'
	. '<body>'
	. '<div align="center">'
	. '<table align="center" width="600" style="border: 1px solid black;">'
	. '<tr><td align="right">';
	echo '<font size="2"><a target="_blank" style="text-decoration:none; color: black;" href="http://vufind2-dev.ucl.cas.cz/Record/002748068">002748068</a></font>';

	echo '<tr><td></br></td></tr>';
	echo '<tr><td><b><a target="_blank" style="text-decoration:none; color: black;" href="http://vufind2-dev.ucl.cas.cz/Search/Results?lookfor=HEJDOV%C3%81%2C+Irena&type=Author&limit=20">HEJDOVÁ</b>, Irena</a></td></tr>';
	echo '<tr><td></br></td></tr>';
	echo '<tr><td><font size="2">Válka má na prodeje knih horší dopad než pandemie / Irena Hejdová.</font></td></tr>';
	echo '<tr><td><font size="2">In: denikn.cz [online] 15. 4. 2022</font></td></tr>';
	echo '<tr><td></br></td></tr>';
	echo '<tr><td><font size="2">[ Článek o dopadu války na Ukrajině na český knižní trh. ]</font></td></tr>';
	echo '<tr><td></br></td></tr>';
	echo '<tr><td><font size="2"> války; ph144863; czenas; knižní obchod; ph114934; czenas; čtenářství; ph222812; czenas; Covid-19; ph1075649; czenas</font></td></tr>';

	#$test = implode($marc->getField('245'), '');
	#print_r($marc->getField('245'));

echo '</td></tr></table><br/>'
	. '</div></body></html>';

?>
