<?php

#Sysno - zarovnat vpravo do rohu
#100 a, b, c - ideálně tvar PŘÍJMENÍ, jméno
#245 - lze vzít bez dalších úprav tak, jak je
#260/264 - opět lze vzít bez dalších úprav (bude jen u knih)
#490 -  opět lze vzít bez dalších úprav (bude jen u knih)
#In: 773t. 773g (bude jen u článků a částí knih)
##[520a.]
#-> všechna pole 6XX (bez 655; za sebe, oddělená středníkem)
#-> všechna pole 787 (každé na nový řádek)

echo "DATAAAAAAAAAAAAAAAAAAAAAAAAAA\n";

?>
