<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><font size="4" style="font-size: 14pt"><u><b>O
aplikaci</b></u></font></p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Vítejte na
stránkách České literární bibliografie, na nichž je aktuálně
spuštěna testovací betaverze discovery systému VuFind. Tento
systém umožňuje jednotné vyhledávání v bibliografických
databázích České literární bibliografie. V dalším výhledu je
postupná integrace dalších zdrojů ČLB (databáze České
literární osobnosti, databáze literárních cen atp.) a postupné
vylepšování stávajících a implementace nových uživatelských
funkcionalit.</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Jakékoli
připomínky či komentáře k tomuto portálu uvítáme na adrese
<a href="mailto:clb@ucl.cas.cz"><font color="#1155cc"><u>clb@ucl.cas.cz</u></font></a>.</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><br/>
<br/>

</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><font size="4" style="font-size: 14pt"><u><b>Zapojené
zdroje</b></u></font></p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Momentálně
jsou k prohledávání přístupné následující denně
aktualizované databáze a zdroje:</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><u>Retrospektivní
bibliografie české literatury 1770–1945</u></p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Prozatím je na
tomto místě zpřístupněna databáze RET, tj. v závěru
devadesátých let ručně přepsaná část předmětové části
Retrospektivní bibliografie, obsahující excerpta k literárním
spolkům a literárním časopisům. V úplnosti je Retrospektivní
bibliografie dostupná v podobě digitalizované lístkové kartotéky
na adrese <a href="http://retrobi.ucl.cas.cz/"><font color="#1155cc"><u>http://retrobi.ucl.cas.cz/</u></font></a>.
 
</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><u>Tzv. současná
bibliografie české literatury (od roku 1945)</u></p>
<h3 class="western" style="margin-top: 0.53cm; margin-bottom: 0.28cm; page-break-inside: auto; background: #ffffff; page-break-after: auto"><a name="_t5ttqbrihy9h"></a>
<font color="#000000"><font size="2" style="font-size: 11pt">Tato
databáze vznikla postupným slučováním historicky samostatných
dílčích bází, jejich postupným doplňováním o nové záznamy
a průběžnou novou excerpcí. Její nejstarší vrstvu tvoří
bibliografické ročenky </font></font><font color="#000000"><font size="2" style="font-size: 11pt"><i>Česká
literární věda</i></font></font><font color="#000000"><font size="2" style="font-size: 11pt">,
pokrývající období let 1961–1980. Na ně chronologicky navazují
lístková excerpta z let osmdesátých. Počátkem devadesátých
let začala být Česká literární bibliografie zpracovávána v
podobě strukturované databáze v systému CDS/ISIS. V něm postupně
vznikly dva databázové formáty: (a) nejprve starší, méně
podrobný, v němž byla zpracována excerpce z let 1991–1996,
lístková excerpce pro 80. léta, část Retrospektivní
bibliografie a též bibliografie českého literárního exilu
(knižně jako: KNOPP, František: </font></font><font color="#000000"><font size="2" style="font-size: 11pt"><i>Česká
literatura v exilu 1948–1989</i></font></font><font color="#000000"><font size="2" style="font-size: 11pt">.
Praha: Makropulos, 1996) a (b) roku 1997 mladší, detailněji
strukturovaný, v němž byla zpracována excerpce od roku 1997 a
posléze do něj byly přepsány i zmiňované bibliografické
ročenky za léta 1961–1980. </font></font>
</h3>
<h3 class="western" style="margin-top: 0.53cm; margin-bottom: 0.28cm; page-break-inside: auto; background: #ffffff; page-break-after: auto"><a name="_gjfvun74ase3"></a>
<font color="#000000"><font size="2" style="font-size: 11pt">Roku
2012 bylo rozhodnuto o přechodu na mezinárodní výměnný formát
MARC21 a systém Aleph, do nějž byly v průběhu let 2015 a 2016
postupně zkonvertovány veškeré starší databáze. V průběhu
konverze prošla data současné bibliografie důkladnou redakcí a
byla doplněna o řadu perzistentních identifikátorů a dalších
strojově doplnitelných údajů tak, aby bylo dosaženo co největší
harmonizace jednotlivých částí báze a zároveň aby bylo
umožněno propojení dat ČLB s dalšími národními a nadnárodními
sítěmi výměny vědeckých informací. </font></font>
</h3>
<h3 class="western" style="margin-top: 0.53cm; margin-bottom: 0.28cm; page-break-inside: auto; background: #ffffff; page-break-after: auto"><a name="_wxr9tudnjywl"></a>
<font color="#000000"><font size="2" style="font-size: 11pt">V letech
2012–2015 pak byla zpracována bibliografie české literatury z
období 1945–1960 (projekt „Bibliografie české literatury
1945–1960“, podpořený MK ČR v rámci programu NAKI; č. </font></font>
</h3>
<h3 class="western" style="margin-top: 0.53cm; margin-bottom: 0.28cm; page-break-inside: auto; background: #ffffff; page-break-after: auto">
<font color="#000000"><font size="2" style="font-size: 11pt">č.
DF12P01OVV011), která vyplnila dlouho existující mezeru mezi
současnou a retrospektivní bibliografií. V nedávné době byly
pro potřeby současné bibliografie zpracovány další velké
databázové celky: od roku 2016 bibliografie českého literárního
samizdatu (v rámci projektu výzkumné infrastruktury „Česká
literární bibliografie“, podpořeného MŠMT ČR; č. LM2015059)
a od roku 2017 bibliografie českého literárního internetu (v
rámci projektu „Česká literární bibliografie: Český
literární internet – data, analýzy, výzkum“, podpořeného v
rámci operačního programu Výzkum, vývoj, vzdělávání; č.
</font></font><font color="#323232"><font size="2" style="font-size: 11pt">CZ.02.1.01/0.0/0.0/16_013/0001743)</font></font><font color="#000000"><font size="2" style="font-size: 11pt">.</font></font></h3>
<h3 class="western" style="margin-top: 0.53cm; margin-bottom: 0.28cm; page-break-inside: auto; background: #ffffff; page-break-after: auto"><a name="_iivi6tdrjgvm"></a>
<font color="#000000"><font size="2" style="font-size: 11pt">Excerpční
záběr současné bibliografie byl pro původní bibliografické
ročenky definován jako sekundární oborová bibliografie české
literatury a literární vědy, v rámci jednotlivých dílčích
projektů však byl tento záběr postupně rozšiřován až na
aktuální stav, kdy současná bibliografie zpracovává veškeré
dostupné materiály o české literatuře v českých a relevantních
zahraničních periodikách, denním tisku, knižní produkci či v
online prostředí (specializované weby, zpravodajské servery
atp.). Podrobněji je stav excerpce patrný buď v databázi
excerpovaných časopisů </font></font><font color="#0563c1"><u><a href="http://excas.ucl.cas.cz/"><font size="2" style="font-size: 11pt">zde</font></a></u></font><font color="#000000"><font size="2" style="font-size: 11pt">,
nebo v následující tabulce.</font></font></h3>
<p style="margin-bottom: 0cm"><br/>

</p>
<table width="841" cellpadding="5" cellspacing="0">
	<col width="157">
	<col width="68">
	<col width="75">
	<col width="75">
	<col width="85">
	<col width="84">
	<col width="225">
	<tr>
		<td width="157" height="28" bgcolor="#984806" style="background: #984806" style="border-top: 1.00pt solid #000000; border-bottom: 1px solid #9bc2e6; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><b>Databáze</b></font></font></p>
		</td>
		<td width="68" bgcolor="#984806" style="background: #984806" style="border-top: 1.00pt solid #000000; border-bottom: 1px solid #9bc2e6; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><b>Primární
			prameny (beletrie)</b></font></font></p>
		</td>
		<td width="75" bgcolor="#984806" style="background: #984806" style="border-top: 1.00pt solid #000000; border-bottom: 1px solid #9bc2e6; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><b>Sekundární
			literatura</b></font></font></p>
		</td>
		<td width="75" bgcolor="#984806" style="background: #984806" style="border-top: 1.00pt solid #000000; border-bottom: 1px solid #9bc2e6; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><b>Světová
			literatura</b></font></font></p>
		</td>
		<td width="85" bgcolor="#984806" style="background: #984806" style="border-top: 1.00pt solid #000000; border-bottom: 1px solid #9bc2e6; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><b>Knihy,
			sborníky, části knih</b></font></font></p>
		</td>
		<td width="84" bgcolor="#984806" style="background: #984806" style="border-top: 1.00pt solid #000000; border-bottom: 1px solid #9bc2e6; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><b>Původní
			struktura dat</b></font></font></p>
		</td>
		<td width="225" bgcolor="#984806" style="background: #984806" style="border-top: 1.00pt solid #000000; border-bottom: 1px solid #9bc2e6; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><b>Poznámka</b></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="157" height="54" bgcolor="#fff2cc" style="background: #fff2cc" style="border: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><b>Retrospektivní
			bibliografie (1771–1945)</b></font></font></p>
		</td>
		<td width="68" bgcolor="#ffffff" style="background: #ffffff" style="border: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="85" bgcolor="#ffffff" style="background: #ffffff" style="border: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="84" bgcolor="#ffffff" style="background: #ffffff" style="border: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">lístky</font></font></p>
		</td>
		<td width="225" bgcolor="#ffffff" style="background: #ffffff" style="border: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif">Digitalizovaná
			lístková kartotéka </font></font><font color="#0563c1"><u><a href="http://retrobi.ucl.cas.cz/"><font face="Calibri, serif">zde</font></a></u></font><font color="#000000"><font face="Calibri, serif">.</font></font></p>
		</td>
	</tr>
	<tr>
		<td width="157" height="54" bgcolor="#fff2cc" style="background: #fff2cc" style="border: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><b>Báze RET</b></font></font></p>
		</td>
		<td width="68" bgcolor="#ffffff" style="background: #ffffff" style="border-top: none; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: none; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: none; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="85" bgcolor="#ffffff" style="background: #ffffff" style="border-top: none; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="84" bgcolor="#ffffff" style="background: #ffffff" style="border-top: none; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ISIS
			– starší</font></font></p>
		</td>
		<td width="225" bgcolor="#ffffff" style="background: #ffffff" style="border: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p style="margin-bottom: 0cm"><font color="#000000"><font face="Calibri, serif">Pouze
			část předmětové části</font></font></p>
			<p><font color="#000000"><font face="Calibri, serif">(5 % celku
			Retrospektivní bibliografie)</font></font></p>
		</td>
	</tr>
	<tr>
		<td width="157" height="54" bgcolor="#fff2cc" style="background: #fff2cc" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><b>Bibliografie
			1945–1960</b></font></font></p>
		</td>
		<td width="68" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="85" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="84" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">MARC21</font></font></p>
		</td>
		<td width="225" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"> </font>
			</p>
		</td>
	</tr>
	<tr>
		<td width="157" height="54" bgcolor="#fff2cc" style="background: #fff2cc" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><b>Bibliografie
			1961–1980</b></font></font></p>
		</td>
		<td width="68" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="85" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO
			(bez beletrie)</font></font></p>
		</td>
		<td width="84" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ISIS
			– mladší</font></font></p>
		</td>
		<td width="225" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif">Přepsané
			ročenky</font></font></p>
		</td>
	</tr>
	<tr>
		<td width="157" height="54" bgcolor="#fff2cc" style="background: #fff2cc" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><b>Bibliografie
			1981–1996</b></font></font></p>
		</td>
		<td width="68" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="85" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO
			(bez beletrie)</font></font></p>
		</td>
		<td width="84" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ISIS
			– starší</font></font></p>
		</td>
		<td width="225" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif">Přepsaná
			lístková excerpta + nejstarší databázová excerpce</font></font></p>
		</td>
	</tr>
	<tr>
		<td width="157" height="54" bgcolor="#fff2cc" style="background: #fff2cc" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><b>Bibliografie
			1997–2012</b></font></font></p>
		</td>
		<td width="68" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="85" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO
			(bez beletrie)</font></font></p>
		</td>
		<td width="84" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ISIS
			– mladší</font></font></p>
		</td>
		<td width="225" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"> </font>
			</p>
		</td>
	</tr>
	<tr>
		<td width="157" height="54" bgcolor="#fff2cc" style="background: #fff2cc" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><b>Bibliografie
			od roku 2012</b></font></font></p>
		</td>
		<td width="68" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO
			(od roku 2016)</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="85" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO
			(od roku 2020 včetně beletrie)</font></font></p>
		</td>
		<td width="84" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">MARC21</font></font></p>
		</td>
		<td width="225" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"> </font>
			</p>
		</td>
	</tr>
	<tr>
		<td width="157" height="54" bgcolor="#fff2cc" style="background: #fff2cc" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><b>Bibliografie
			exilu</b></font></font></p>
		</td>
		<td width="68" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="85" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO
			(bez beletrie)</font></font></p>
		</td>
		<td width="84" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ISIS
			– starší</font></font></p>
		</td>
		<td width="225" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"> </font>
			</p>
		</td>
	</tr>
	<tr>
		<td width="157" height="54" bgcolor="#fff2cc" style="background: #fff2cc" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><b>Bibliografie
			samizdatu</b></font></font></p>
		</td>
		<td width="68" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="85" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="84" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">MARC21</font></font></p>
		</td>
		<td width="225" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"> </font>
			</p>
		</td>
	</tr>
	<tr>
		<td width="157" height="53" bgcolor="#fff2cc" style="background: #fff2cc" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: 1.00pt solid #000000; border-right: 1.00pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><b>Bibliografie
			internetu</b></font></font></p>
		</td>
		<td width="68" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">ANO</font></font></p>
		</td>
		<td width="75" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="85" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">NE</font></font></p>
		</td>
		<td width="84" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif">MARC21</font></font></p>
		</td>
		<td width="225" bgcolor="#ffffff" style="background: #ffffff" style="border-top: 1px solid #9bc2e6; border-bottom: 1.00pt solid #000000; border-left: none; border-right: 1.00pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"> </font>
			</p>
		</td>
	</tr>
</table>
<p style="margin-bottom: 0cm"><br/>

</p>
<p style="margin-bottom: 0cm"><br/>

</p>
<p style="margin-bottom: 0cm"><br/>

</p>
<p style="margin-bottom: 0cm"><br/>

</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><br/>
<br/>

</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Historicky byly
databáze ČLB zpracovávány ve třech různých databázových
strukturách: starší a mladší masce databáze ISIS a nejnověji
ve formátu MARC21. Před konverzí dat do formátu MARC21 byla
obvykle i při zpětném doplňování dílčích bází respektována
jednotná databázová struktura, od přechodu na MARC21 již toto
není bráno v potaz. Typ databázové struktury užívané pro
vybranou dílčí část databáze je uveden v tabulce výše
(sloupec “Původní struktura dat”), podrobnější komentovaný
rozpis dle jednotlivých polí je k dispozici v následujícím.</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><br/>
<br/>

</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><font size="4" style="font-size: 14pt"><u><b>Struktura
záznamu</b></u></font></p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Každý
jednotlivý záznam v bázi České literární bibliografie je
anotovaný a obsahuje do dílčích polí či podpolí členěné
informace o popisné jednotce. Některá pole jsou obligatorní (v
tabulce níže podbarvena oranžově), jiná jsou vyplněna na
základě úvahy zpracovatele záznamu (obvykle jde o tzv. věcný
popis).</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Veškerá
relevantní pole (autor a zejména pole pro předmětový/věcný
popis) jsou od přechodu na formát MARC21, tj. od roku 2012)
systematicky propojována na tzv. soubor národních autorit, díky
čemuž je v bázi možné např. odlišit jmenovce či homonymní
termíny. Starší záznamy byly na soubor národních autorit
napojovány v průběhu konverze. Pakliže to nebylo možné, je
tento údaj doplňován ručně během redakce databáze.</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Následující
tabulka nabízí ve zjednodušené formě srovnání historicky
užívaných databázových formátů v systému ISIS a aktuální
struktury databáze v MARC21. V průběhu konverze bází ČLB byla
tato struktura dle technických možností v maximální možné míře
unifikována. Případné odlišnosti jsou okomentovány v poznámce
pro jednotlivá pole.</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><br/>
<br/>

</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><br/>
<br/>

</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><br/>
<br/>

</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><br/>
<br/>

</p>
<table width="841" cellpadding="5" cellspacing="0">
	<col width="191">
	<col width="98">
	<col width="98">
	<col width="98">
	<col width="303">
	<tr>
		<td width="191" height="33" bgcolor="#984806" style="background: #984806" style="border: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><span lang="cs-CZ"><b>Název
			pole</b></span></font></font></p>
		</td>
		<td width="98" bgcolor="#984806" style="background: #984806" style="border-top: 1.50pt solid #000000; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><span lang="cs-CZ"><b>ISIS
			– starší</b></span></font></font></p>
		</td>
		<td width="98" bgcolor="#984806" style="background: #984806" style="border-top: 1.50pt solid #000000; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><span lang="cs-CZ"><b>ISIS
			– mladší</b></span></font></font></p>
		</td>
		<td width="98" bgcolor="#984806" style="background: #984806" style="border-top: 1.50pt solid #000000; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><span lang="cs-CZ"><b>MARC21</b></span></font></font></p>
		</td>
		<td width="303" bgcolor="#984806" style="background: #984806" style="border-top: 1.50pt solid #000000; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#ffffff"><font face="Calibri, serif"><span lang="cs-CZ"><b>Poznámka</b></span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Systémové
			číslo</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: 1.50pt solid #000000; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: 1.50pt solid #000000; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: 1.50pt solid #000000; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: 1.50pt solid #000000; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Po
			konverzi nové, stará v 035.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Typ
			záznamu</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">U
			formátu &quot;ISIS – starší&quot; doplněno při konverzi.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Názvy</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">V
			MARC21 řada variant, v ISIS případně řešeno poznámkou.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Autoři</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Při
			konverzi sjednoceno dle pravidel MARC21.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Kód
			autorské role</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Při
			konverzi sjednoceno dle pravidel MARC21.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Údaje
			o odpovědnosti</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Při
			konverzi sjednoceno dle pravidel MARC21.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Název
			zdroje</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Při
			konverzi sjednoceno dle pravidel MARC21.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Bibliografická
			citace</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">V
			ISIS jednotlivé části původně jako samostatná pole, při
			konverzi sjednoceno dle pravidel MARC21.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Označení
			vydání</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000">&nbsp;</font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Nakladatelské
			údaje</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000">&nbsp;</font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Fyzický
			popis</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000">&nbsp;</font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Edice</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000">&nbsp;</font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Poznámka</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000">&nbsp;</font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Forma/žánr</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">V
			bázi ISIS řízený slovník s omezeným množstvím hodnot.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Jazyk</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">U
			formátu ISIS – starší při konverzi doplněn dle zdrojového
			dokumentu.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Země
			vydání</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">U
			formátu ISIS dle možnosti doplněno na základě názvu časopisu
			či místa vydání.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Anotace</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000">&nbsp;</font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Rozpis
			částí</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">U
			formátu ISIS – starší případně v anotaci.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Předmět
			– Odkazovaná díla</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">U
			formátu ISIS – starší druhé a další dílo v anotaci,
			poloautomaticky vyčleněno.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Předmět
			– Akce</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">U
			formátu ISIS – starší případně v anotaci, poloautomaticky
			vyčleněno.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Předmět
			– Osoby</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000">&nbsp;</font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Předmět
			– Instituce</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">U
			formátu ISIS – starší případně v anotaci, poloautomaticky
			vyčleněno.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Předmět
			</b></span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><i><b>–</b></i></span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>
			Chronologický termín</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"> </font>
			</p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">U
			formátu ISIS </span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><i>–</i></span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">
			starší nesledováno, u formátu ISIS </span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><i>–</i></span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">
			mladší doplněno na základě MDT.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Předmět
			</b></span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><i><b>–</b></i></span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>
			Geografický termín</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">U
			formátu ISIS </span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><i>–</i></span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">
			starší v anotaci, u formátu ISIS </span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><i>–</i></span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">
			mladší jako klíčová slova; při konverzi vyčleněno jako
			samostatné pole.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Tematické
			skupiny</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Původní
			systém věcného popisu vycházející z tzv. bibliografických
			ročenek, při konverzi převeden na slovně vyjádřený věcný
			termín.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Klíčová
			slova</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">U
			formátu ISIS sem zapisovány hodnoty věcného popisu, které
			nebylo možné vyčlenit jinam, v MARC21 jen ty hodnoty vlastního
			věcného popisu, které nejsou v autoritní bázi.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>MDT</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">U
			formátu ISIS </span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><i>–</i></span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">
			starší neužíváno, u formátu ISIS </span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><i>–</i></span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">
			mladší používáno obvykle buď MDT, nebo klíčové slovo. Po
			přechodu na MARC21 využíváno ve všech případech.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Skupina
			konspektu</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Pouze
			u záznamů v MARC21.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Číslo
			ČNB</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Pouze
			u záznamů v MARC21.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>ISBN</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Pouze
			u záznamů v MARC21, ojediněle u formátu ISIS </span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><i>–</i></span></font></font><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">
			mladší.</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>ISSN</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000">&nbsp;</font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Typ
			obsahu</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Pouze
			u záznamů dle norem RDA (od 1. 5. 2015 dále).</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Typ
			média</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Pouze
			u záznamů dle norem RDA (od 1. 5. 2015 dále).</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="75" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>Typ
			nosiče</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" bgcolor="#ffc000" style="background: #ffc000" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1px solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Pouze
			u záznamů dle norem RDA (od 1. 5. 2015 dále).</span></font></font></p>
		</td>
	</tr>
	<tr>
		<td width="191" height="73" bgcolor="#ffe699" style="background: #ffe699" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: 1.50pt solid #000000; border-right: 1.50pt solid #000000; padding: 0cm 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ"><b>URL
			adresa</b></span></font></font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000">&nbsp;</font></p>
		</td>
		<td width="98" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: none; border-right: 1px solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p align="center"><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">X</span></font></font></p>
		</td>
		<td width="303" style="border-top: none; border-bottom: 1.50pt solid #000000; border-left: none; border-right: 1.50pt solid #000000; padding-top: 0cm; padding-bottom: 0cm; padding-left: 0cm; padding-right: 0.12cm">
			<p><font color="#000000"><font face="Calibri, serif"><span lang="cs-CZ">Pouze
			u záznamů v MARC21.</span></font></font></p>
		</td>
	</tr>
</table>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><br/>
<br/>

</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><font size="4" style="font-size: 14pt"><u><b>Vyhledávání
v bázi</b></u></font></p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">V bázi je možno
vyhledávat několika různými způsoby, a to:</p>
<p style="margin-left: 0.64cm; margin-top: 0.42cm; margin-bottom: 0.42cm">
a)<font size="1" style="font-size: 7pt">       </font>pomocí
jednoduchého vyhledávání v centrálním vyhledávacím okně
(není-li zvoleno jinak, systém primárně prohledává všechny
záznamy; položením prázdného dotazu lze zobrazit rešerši v
celé databázi)</p>
<p style="margin-left: 0.64cm; margin-top: 0.42cm; margin-bottom: 0.42cm">
b)<font size="1" style="font-size: 7pt">      </font>pomocí
pokročilého vyhledávání kombinací kritérií ze zvolených
databázových polí</p>
<p style="margin-left: 0.64cm; margin-top: 0.42cm; margin-bottom: 0.42cm">
c)<font size="1" style="font-size: 7pt">       </font>pomocí
fasetové navigace v pravém sloupci</p>
<p style="margin-left: 0.64cm; margin-top: 0.42cm; margin-bottom: 0.42cm">
d)<font size="1" style="font-size: 7pt">      </font>k záznamům je
též možno přistupovat prostřednictvím rejstříků (nabídka v
zápatí)</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Detailněji jsou
možnosti vyhledávání v systému včetně možnosti využití
booleovské logiky (AND, OR, NOT), tzv. divokých karet, vážení
slov atp.  popsány <font color="#0563c1"><u><a href="https://vufind.ucl.cas.cz/Help/Home?topic=search&amp;_=1583345681">zde</a></u></font>.
</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"> 
</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><font size="4" style="font-size: 14pt"><u><b>Export</b></u></font></p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Ze systému je
prozatím možno exportovat omezené množství 200 záznamů ve
formátech MARCXML a binárním MARC21. Zajímavou alternativou je
export dat do PDF prostřednictvím nabídky „Vytisknout“.
Uživatel si též může rešerši odeslat na email či si ji uložit
v uživatelském účtu.</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"> 
</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><font size="4" style="font-size: 14pt"><u><b>Registrace</b></u></font></p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Registrace do
systému není povinná, umožňuje však mimo jiné ukládat si
uvnitř systému své vlastní rešerše, vytvářet si množinu
oblíbených záznamů, připojovat k jednotlivým záznamům
komentáře či vrátit se ke starším dotazům.</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><u> </u>
</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><font size="4" style="font-size: 14pt"><u><b>Možnosti
nastavení</b></u></font></p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Systém umožňuje
mj. zvolit si z cca 30 jazykových variant rozhraní (nabídka
„Jazyk“ vpravo nahoře), nastavit počet jednotlivých záznamů
na stránku či řadit záznamy od nejmladšího/nejstaršího (vždy
až na úroveň dne), dle relevance, názvu článku či jména
autora.</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><a name="_GoBack"></a>
<br/>
<br/>

</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm"><font size="4" style="font-size: 14pt"><u><b>Další
funkcionality</b></u></font></p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Na základě
přítomnosti identifikátorů typu ISSN, ISBN či čísla České
národní bibliografie jsou prezentovaná data prostřednictvím
sluřby <b>Obálkyknih.cz</b> o další související materiály,
zejména obálky knih a časopisů.</p>
<p style="margin-top: 0.42cm; margin-bottom: 0.42cm">Aktuálně
zpracovávaná data, tj. zejména bibliografie literárního
internetu a bibliografie samizdatová, jsou systematicky doplňována
o linky na původní umístění daného dokumentu v síti, popř.
též na na jeho archivní kopii na portále <b>Webarchiv.cz</b>.  
</p>
