<h1>How We Use Cookies</h1>
<p>We use cookies to store and retrieve small bits of information on your computer when you visit. This information
is used to make the site work as you expect it to. It is not personally identifiable to you, but it can be used to give you a more
personalised web experience.</p>
<p>If you continue to use this site without taking action to prevent the storage of this information, you are effectively agreeing to
this use.</p>
<p>Below is a list of the different types of cookies used on this site, and an explanation of what they are used for.
If you would like any more information, please get in touch.</p>
<dl>
    <dt>Strictly Necessary Cookies</dt>
    <dd>
        <p>These cookies are necessary for the website to function. They are usually only set in response to actions 
        made by you which amount to a request for services, such as logging in or filling in forms.</p>
        <p>You can set your browser to block or alert you about these cookies, but some parts of the site will not 
        work. These cookies do not store any personally identifiable information.</p>
        <dl>
            <dt>PHPSESSID</dt><dd> This temporary session cookie is used to record a session/visit to the website. This information is required to allow a user to stay logged in to a web site without needing to submit their username and password for each page visited. Without this cookie, a user is unable to proceed to areas of the web site that require authenticated access.</dd>
        </dl>
    </dd>
    <dt>Performance Cookies</dt>
    <dd>
        <p>These cookies allow us to improve performance of our site.</p>
        <p>If you do not allow these cookies then some minor effect can be noted on loading times of the web pages.</p>
        <dl>
            <dt>ui</dt><dd>the preferable lay-out of the webpage, normal it is always set to "standard".</dd>
            <dt>loggedOut</dt><dd>avoids extra tests to note that you are logged out.</dd>
        </dl>
    </dd>
</dl>
