<h1>Jak používáme Cookies</h1>
<p>Používáme soubory Cookies k uložení a získání malých kousků informací na Vašem počítači při návštěvě stránky. Tyto informace slouží k fungování stránky. Nejsou s Vámi osobně svázány, ale pomáhají přizpůsobit chování stránky na základě Vašeho používání.</p>
<p>Pokud budete pokračovat v používání stránky bez zamezení uložení těchto souborů, dáváte nám souhlas s jejich použitím.</p>
<p>Níže je seznam všech typů Cookies na této stránce a vysvětlení k čemu se používají. Pokud máte více otázek napište nám.</p>
<dl>
    <dt><u>FUNKČNÍ, TECHNICKÉ</u></dt>
    <dd>
        <p>Tyto Cookies jsou nezbytné pro správné fungování stránky. Jsou vytvořené během Vaší aktivity. Například přihlašování, vyhledávání, nebo vyplňování vstupních polí.</p>
	<p>Můžete nastavit prohlížeč, aby blokoval, nebo upozorňoval na takové Cookies, ale nekteré části stránky nemusí spolehlivě fungovat. Tyto Cookies neukládají žádné osobní údaje.</p>
        <dl>
            <dt>VUFIND_SESSION</dt><dd><p>Zaznamenává navštěvu stránky. Tato informace je potřeba, aby uživatel mohl zůstat přihlášný bez nutnosti opakovaně zadávat přihlašovací údaje při návštěvě různých stránek. Bez této Cookie není možné navštěvovat stánky které vyžadují přihlášení.</p></dd>
            <dt>ui</dt><dd><p>Aktuálně zvolené rozložení stránky. Hodnota je "standard", nebo "mobile".</p></dd>
            <dt>pll_language / language</dt><dd><p>Aktuálně zvolený jazyk.</p></dd>
            <dt>loggedOut</dt><dd><p>Kontrola odhlášení.</p></dd>
        </dl>
    </dd>
</dl>
