
<?php
 // $this->layout()->breadcrumbs = true;
  $this->layout()->searchClassId = 'SolrAuth';
  // Pick a tab to display -- Details if available, otherwise first option (if any):
  $metadata = $this->tabs['Details'] ?? current($this->tabs) ?? null;

?>

<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="auth-body">

    <h3 property="name"><?=$this->escapeHtml($this->driver->getTitle())?></h3>

    <?php $birth = $this->driver->CLB_getBirth(); $birth = isset($birth) ? $this->escapeHtml($birth) : false; ?>
    <?php if ($birth): ?>
      <p><?=$birth?></p>
    <?php endif; ?>

    <?php $death = $this->driver->CLB_getDeath(); $death = isset($death) ? $this->escapeHtml($death) : false; ?>
    <?php if ($death): ?>
      <p><?=$death?></p>
    <?php endif; ?>

    <?php $bio = $this->driver->CLB_getBio(); $bio = isset($bio[0]) ? $this->escapeHtml($bio[0]) : false; ?>
    <?php if ($bio): ?>
      <p><?=$bio?></p>
    <?php endif; ?>

    <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle): ?>
      <div class="title-alt">
        <?=$this->escapeHtml($altTitle)?>
      </div>
    <?php endforeach; ?>

    <?php /* Display Main Details */ ?>
    <?php
      $formatter = $this->recordDataFormatter();
      $coreFields = $formatter->getData($driver, $formatter->getDefaults('auth-core'));
    ?>
    <?php if (!empty($coreFields)): ?>
      <table class="table table-striped">
        <caption class="sr-only"><?=$this->transEsc('Authority Details')?></caption>
        <?php foreach ($coreFields as $current): ?>
          <tr><th><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>
    <?php /* End Main Details */ ?>

<?php if (count($this->tabs) > 0): ?>
      <a name="tabnav"></a>
      <div class="record-tabs">
        <ul class="nav nav-tabs">
          <?php foreach ($this->tabs as $tab => $obj): ?>
            <?php
              $desc = $obj->getDescription();
              $tabName = preg_replace("/\W/", "-", strtolower($tab));
              $tabClasses = [ 'record-tab', $tabName ];
              if (0 === strcasecmp($this->activeTab, $tab)) {
                if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                  $tabClasses[] = 'active';
                }
                $tabClasses[] = 'initiallyActive';
                $activeTabObj = $obj;
              }
              if (!$obj->isVisible()) { $tabClasses[] = 'hidden'; }
              if (!$obj->supportsAjax()) { $tabClasses[] = 'noajax'; }
            ?>
		<li class="<?=implode(' ', $tabClasses)?>" data-tab="<?=$this->escapeHtmlAttr($tabName)?>">
              <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, $tab))?>#tabnav" data-lightbox-ignore>
                <?=$this->transEsc($desc)?>
              </a>
            </li>
          <?php endforeach; ?>
        </ul>

	<div class="tab-content">
          <?php if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
            <div class="tab-pane active <?=$this->escapeHtmlAttr($this->activeTab) ?>-tab">
		<?=empty($metadata) ? $this->transEsc('no_description') :  $this->record($this->driver)->getTab($metadata)?>
            </div>
          <?php endif; ?>
        </div>
      </div>
<?php endif; ?>

  </div>
</div>

