#!/bin/bash
#
# Crontab monthly runner
#
# 15 6 2 * * root oai-monthly >> /var/log/oai-monthly.log 2>&1 &
#

DATA_PATH='/tmp/5xx'

SEVEN_RAW="/var/www/html/7/raw"
SEVEN_DATA="/var/www/html/7/archive/$(date +'%Y/%m')/data"

# ------------------------

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

#
# "5xx"
#

mkdir -p "$DATA_PATH" 2> /dev/null

oai-5xx \
	--set 'UCLA' \
	--from "$(date --date="$(date +'%Y-%m-01') -1 month" +'%Y-%m-%d 00:00:00')" \
	--until "$(date +'%Y-%m-01 00:00:00')" \
	--check \
	--notify

rm -r "$DATA_PATH" 2> /dev/null

echo "5xx done."

#
# "7"
#

mkdir -p "$SEVEN_RAW" 2> /dev/null
mkdir -p "$SEVEN_DATA" 2> /dev/null

oai-7 \
	--set 'UCLA' \
	--from "$(date --date="$(date +'%Y-%m-01') -1 month" +'%Y-%m-%d 00:00:00')" \
	--until "$(date +'%Y-%m-01 00:00:00')" \
	--check

# statistic
for FILE in $(ls "$SEVEN_RAW"/*.csv); do
	DATA=$( cut -d\; -f1 "$FILE" | sort | uniq)
	while read LINE; do
		echo "$(grep -F -- "$LINE" "$FILE" | wc -l);$LINE"
	done <<< "$DATA" | sort -r -n >> "${SEVEN_RAW/.csv/_stat.csv}"
done

mv "$SEVEN_RAW"/* "$SEVEN_DATA" 2> /dev/null

echo "7-Harvest done."

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

exit 0

