#!/bin/bash
#
# Crontab daily runner
#
# 00 5 * * * root oai-daily >> /var/log/oai-daily.log 2>&1 &
#

DATA_PATH='/var/www/html/denní'
ARCHIVE_PATH='/var/www/html/archiv'

FILENAME="$(date --date='yesterday' '+%Y-%m-%d').html"
CSVNAME="$(date --date='yesterday' '+%Y-%m-%d').csv"

VUFIND_PATH='/var/www/html/vufind/'
VUFIND="vufind-$(date --date='yesterday' '+%Y-%m-%d').tar.gz"

# ------------------------

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

# VUFIND

mkdir -p "$VUFIND_PATH" 2> /dev/null

oai-citace \
	--set UCLA \
	--from "$(date --date='yesterday' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='today' '+%Y-%m-%d 00:00:00')" \
	--check

[ -s *.mrc ] &&	tar --remove-files -czf "$VUFIND_PATH/$VUFIND" *.mrc 2>/dev/null

rm *.mrc 2> /dev/null

# CONTROL

oai-marc \
	--set UCLA \
	--from "$(date --date='yesterday' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='today' '+%Y-%m-%d 00:00:00')" \
	--check \
	--notify

mkdir -p "$DATA_PATH" 2> /dev/null
mkdir -p "$ARCHIVE_PATH/$(date --date='yesterday' '+%Y/%m')" 2> /dev/null

sed -i "s/CSVPLACEHOLDER/$CSVNAME/" oai-marc.html 2> /dev/null

mv -f oai-marc.html "$ARCHIVE_PATH/$(date --date='yesterday' '+%Y/%m')/$FILENAME" 2> /dev/null
mv -f oai-marc.csv "$ARCHIVE_PATH/$(date --date='yesterday' '+%Y/%m')/$CSVNAME" 2> /dev/null

ln -s "$ARCHIVE_PATH/$(date --date='yesterday' '+%Y/%m')/$FILENAME" "$DATA_PATH/$FILENAME" 2> /dev/null
ln -s "$ARCHIVE_PATH/$(date --date='yesterday' '+%Y/%m')/$CSVNAME" "$DATA_PATH/$CSVNAME" 2> /dev/null

find $DATA_PATH -maxdepth 1 -type l -mtime +14 -exec rm {} \;

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

exit 0

