#!/bin/bash
#
# Crontab monthly runner
#
# 00 5 1 * * root oai-monthly-kat >> /var/log/oai-monthly-kat.log 2>&1 &
#

KAT="/var/www/html/kat/$(date --date="$(date) -2 day" +'%Y/%m')/data"

# ------------------------

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

#
# "KAT"
#

mkdir -p "$KAT" 2> /dev/null

oai-kat \
	--set 'UCLA' \
	--from "$(date --date="$(date +'%Y-%m-01') -1 month" +'%Y-%m-%d 00:00:00')" \
	--until "$(date +'%Y-%m-01 00:00:00')" \
	--check

echo "KAT done."

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

exit 0

