#!/bin/bash
#
# Crontab weekly runner
#
# 00 5 * * * root oai-weekly >> /var/log/oai-weekly.log 2>&1 &
#

DATA_PATH='/var/www/html/týdenní'

FILENAME="$(date --date='8 days ago' '+%Y-%m-%d')_$(date --date='2 days ago' '+%Y-%m-%d').html"
CSVNAME="$(date --date='8 days ago' '+%Y-%m-%d')_$(date --date='2 days ago' '+%Y-%m-%d').csv"

# ------------------------

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

oai-marc \
	--set UCLA \
	--from "$(date --date='8 days ago' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='2 days ago' '+%Y-%m-%d 00:00:00')" \
	--check

mkdir -p "$DATA_PATH" 2>/dev/null

sed -i "s/CSVPLACEHOLDER/$CSVNAME/" oai-marc.html 2> /dev/null

mv -f oai-marc.html "$DATA_PATH/$FILENAME" 2> /dev/null
mv -f oai-marc.csv "$DATA_PATH/$CSVNAME" 2> /dev/null

find "$DATA_PATH" -maxdepth 1 -type f -mtime +56 -delete

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

cat << EOF | mail -s 'Kontrolní zpráva' xxx
Dobrý den,

Kontrolní zpráva je dostupná na adrese:

http://pokuston.ucl.cas.cz:38080/t%c3%bddenn%c3%ad/

---------------------------
TATO ZPRÁVA BYLA VYGENEROVÁNA AUTOMATICKY,
NEODPOVÍDEJTE NA NI.
EOF

exit 0

