#!/bin/bash
#
# Crontab daily runner
#
# 00 5 * * * root oai-daily >> /var/log/oai-daily.log 2>&1 &
#

DATA_PATH='/var/www/html/denní'
ARCHIVE_PATH='/var/www/html/archiv'

# ------------------------

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

oai-marc \
	--set UCLA \
	--from "$(date --date='yesterday' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='today' '+%Y-%m-%d 00:00:00')" \
	--check \
	--notify

mkdir -p "$DATA_PATH" 2>/dev/null

mv oai-marc.html "$DATA_PATH/$(date --date='yesterday' '+%Y-%m-%d').html" 2> /dev/null

# create archive dir
# move to archive
# create simlink
# drop old simlinks
#find $DATA_PATH -maxdepth 1 -type f -mtime +14 -exec mv {} "$ARCHIVE_PATH" \;

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

exit 0

