#!/bin/bash
#
# Crontab weekly runner
#
# 00 5 * * * root oai-weekly >> /var/log/oai-weekly.log 2>&1 &
#

ROOT_PATH='/var/www/html'
DATA_PATH='/var/www/html/týdenní'

# ------------------------

echo "start $(date '+%Y-%m-%d %H:%M:%S')"

oai-marc \
	--set UCLA \
	--from "$(date --date='2 days ago' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='8 days ago' '+%Y-%m-%d 00:00:00')" \
	--check

mkdir -p "$DATA_PATH" 2>/dev/null

mv oai-marc.html "$DATA_PATH/$(date --date='8 days ago' '+%Y-%m-%d')-$(date --date='2 days ago' '+%Y-%m-%d').html" 2> /dev/null

#find $DATA_PATH -maxdepth 1 -type f -mtime +14 -delete

echo "end $(date '+%Y-%m-%d %H:%M:%S')"

#cat << EOL | mail -s 'Kontrolní zpráva' xxx
#
#Dobrý den,
#
#Kontrolní zpráva za poslední týden:
#
#https://pokuston.ucl.cas.cz:38080/weekly.html
#
#TATO ZPRÁVA JE GENEROVÁNA AUTOMATICKY
#EOL 

exit 0

