#!/bin/bash
#
# Crontab daily runner
#
# 00 5 * * * root oai-daily >> /var/log/oai-daily.log 2>&1 &
#

DATA_PATH='/var/www/html/daily'
ROOT_PATH='/var/www/html'

HEADER='<html>
<head><meta charset="utf-8"></head>
<body style="background-color:#000;color:#6DAE42;">
<br><b><u>OAI-PMH 2.0 MARCXML</u></b><br>
<ul>'

FOOTER='</ul>
</body>
</html>'

TEMPLATE='<li><a href="daily/FN" style="color:white;text-decoration:none;">FNBASE</a></li>'

oai-marc \
	--set UCLA \
	--from "$(date --date='yesterday' '+%Y-%m-%d 00:00:00')" \
	--until "$(date --date='today' '+%Y-%m-%d 00:00:00')" \
	--check \
	--notify

mkdir $ROOT_PATH 2>/dev/null
mkdir $DATA_PATH 2>/dev/null

mv oai-marc.html "$DATA_PATH/$(date --date='yesterday' '+%Y-%m-%d').html" 2> /dev/null

find $DATA_PATH -maxdepth 1 -type f -mtime +14 -delete

echo "$HEADER" > "$ROOT_PATH/index.html"

for F in $(find $DATA_PATH -type f -exec basename {} \; | sort); do
	echo "$TEMPLATE" | sed "s/FN/$F/" | sed "s/FNBASE/$(basename $F .html)/"  >> "$ROOT_PATH/index.html"
done

echo "$FOOTER" >> "$ROOT_PATH/index.html"

exit 0

