#!/usr/bin/python3
#
# OAI-PMH 2.0 modular loader.
#

import argparse,sqlite3,sys,io

from datetime import datetime
from oaipmh.client import Client
from oaipmh.metadata import MetadataRegistry
from pymarc import marcxml
from lxml.etree import tostring

from mod import five,cat,seven

# VAR -------------------

URL='https://aleph.lib.cas.cz/OAI'
DB='/var/www/data/devel.db'

# DEF -------------------

def MarcXML(xml):
	handler = marcxml.XmlHandler()
	marcxml.parse_xml(io.StringIO(tostring(xml, encoding='utf-8').decode('utf-8')), handler)
	return handler.records[0]

def valid_date(s):
	try:
		return datetime.strptime(s, '%Y-%m-%d %H:%M:%S')
	except:
		raise argparse.ArgumentTypeError('Invalid date format.')

# ARG -------------------

parser = argparse.ArgumentParser(description="OAI PMH 2.0 Loader.")
parser.add_argument('--set', help='Records set.')
parser.add_argument('--from', help='Records from UTC datetime. [YYYY-mm-dd HH:MM:SS]', type=valid_date, dest='from_date')
parser.add_argument('--until', help='Records until UTC datetime. [YYYY-mm-dd HH:MM:SS]', type=valid_date, dest='until_date')
args = parser.parse_args()

if not args.set:
	parser.error('argument --set is required.')
if not args.from_date:
	parser.error('argument --from is required.')
if not args.until_date:
	parser.error('argument --until is required.')

# INIT -------------------

try:
	db = sqlite3.connect(DB)
	db.row_factory = sqlite3.Row
except:
	print('Failed to open database.')
	sys.exit(1)


registry = MetadataRegistry()
registry.registerReader('marc21', MarcXML)

oai = Client(URL, registry)

try:
	records = oai.listRecords(metadataPrefix='marc21', set=args.set, from_=args.from_date, until=args.until_date)
except:
	records=[]

# MAIN -------------------

DATA=[]

for record in records:
	# skip deleted
	if record[0].isDeleted(): continue
	# write DATA
	DATA.append(record[1])

cat.run(DATA,db)
five.run(DATA)
seven.run(DATA)

sys.exit(0)

