#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# OAI-PMH 2.0 MARCXML subfield '7' control.
#

# INCLUDE -------------------

from __future__ import print_function

import argparse,StringIO,sys,os,re

from pymarc import marcxml

# VAR -------------------

IN='/home/bruna/test/uclall.xml'

RAW='/var/www/html/7/ucl/raw/'
OUT='/var/www/html/7/ucl/data/'

INDEX='/var/www/html/7/ucl/index.html'

TAGLIST=[]

HTML_TOP='''<!doctype html>
<html>
<head><meta charset="utf-8"></head>
<body style="background-color:black;color:#6DAE42;">
<br>
'''
HTML_BOTTOM='<br></body></html>'

SRT_TOP='''<!doctype html>
<html>
<head><meta charset="utf-8"></head>
<body style="background-color:black;color:#6DAE42;">
<br><table>
'''
SRT_BOTTOM='</table><br></body></html>'

INDEX_TOP='''<!doctype html>
<html>
<head><meta charset="utf-8"></head>
<body style="background-color:black;color:#6DAE42;">
<br>
<b><u>OAI-PMH 2.0 MARCXML</u></b>
<br><br><font size="3" color="white">Výstup kontroly podpole "7" záznamů MARCXML v databázi Aleph.</font>
<br><br>
<table border="1" cellpadding="8px" style="border-collapse:collapse;">
<tr>
<td width="30" bgcolor="#333333;" align="center"><font color="gold">Pole</font></td>
<td width="200" bgcolor="#333333;" align="center" colspan="4"><font color="gold">Podpole 7</font></td>
<td width="200" bgcolor="#333333;" align="center" colspan="4"><font color="gold">Bez podpole 7</font></td>
</tr>
'''

# DEF -------------------

def MarcXML(xml):
	handler = marcxml.XmlHandler()
	marcxml.parse_xml(StringIO.StringIO(tostring(xml, encoding='utf-8')), handler)
	return handler.records[0]

def validate(record):

	metadata = record

	ALEPH = record['001'].value()

	for TAG, VALUE, SEVEN in [(f.tag, f.value(), f['7']) for f in metadata.fields]:
		if re.match('(1..|6..|700|710|711|730)', TAG):
			if TAG != '653':
				if TAG not in TAGLIST: TAGLIST.append(TAG)
				if not SEVEN and VALUE:
					try:
						with open(RAW + TAG + '.csv', 'a') as f:
							f.write(VALUE.encode('utf-8')+ '|' + str(ALEPH) + '\n')
					except:
						print("Non Unicode trash ID: " + ALEPH + ' TAG: ' + TAG)
				if SEVEN and VALUE:
					try:
						with open(RAW + TAG + '.7.csv', 'a') as f:
							f.write(VALUE.encode('utf-8') + '|' + str(ALEPH) + '\n')
					except:
						print("Non Unicode trash ID: " + ALEPH + ' TAG: ' + TAG)

print("Processing data.. [this may take a while]")

marcxml.map_xml(validate, IN)

print("Done.")
print("Generating statistic..")

ALL = 0
ALL_7 = 0

ind = open(INDEX, 'a', 0)
ind.write(INDEX_TOP)

#TAGLIST = ['100', '600', '650', '651', '655', '648', '610', '611', '700', '630', '110', '710', '111', u'6OR', '130', '711']

for TAG in sorted(TAGLIST):

	CNT = 0
	CNT_7 = 0

	# NO SEVEN

	DB = {}
	SORT = {}

	htm = open(OUT + TAG + '.html', 'a')
	htm.write(HTML_TOP)
	srt = open(OUT + TAG + '.stat.html', 'a')
	srt.write(SRT_TOP)
	
	#load raw data
	print('Loading ' + TAG + ' ..')
	with open(RAW + TAG + '.csv', 'r') as f:
		for line in f:
			value,aleph = line.split('|')
			if value not in DB: DB[value] = []
			DB[value].append(aleph.strip())
	print("Done.")
	print("Generating html file..")
	for value in DB:
		SORT[value] = len(DB[value])
		for aleph in DB[value]:
			htm.write('<p><a style="color:#6DAE42;" target="_blank" href="https://aleph22.lib.cas.cz/F/?func=direct&doc_number=' +
				aleph + '&local_base=AV">' + aleph + '</a><font color="white">' + value + '</font></p>\n'
			)
			CNT+=1
	htm.write(HTML_BOTTOM)	
	htm.close()
	print("Done.")
	print("Generating stat file..")
	for value in sorted(SORT, key=SORT.get, reverse=True):
		srt.write('<tr><td align="right"><font color="white">' + str(SORT[value]) + '</font></td>' +
			'<td><a style="color:#6DAE42;" target="_blank" href="https://vufind.ucl.cas.cz/Search/Results?lookfor=' + value +
			'&type=Author"></td>\n'
		)
	srt.write(SRT_BOTTOM)	
	srt.close()
	print("Done.")

	# SEVEN

	DB = {}
	SORT = {}

	htm = open(OUT + TAG + '.7.html', 'a')
	htm.write(HTML_TOP)
	srt = open(OUT + TAG + '.7.stat.html', 'a')
	srt.write(SRT_TOP)
	
	#load raw data
	print('Loading 7 ' + TAG + ' ..')
	with open(RAW + TAG + '.7.csv', 'r') as f:
		for line in f:
			value,aleph = line.split('|')
			if value not in DB: DB[value] = []
			DB[value].append(aleph.strip())
	print("Done.")
	print("Generating 7 html file..")
	for value in DB:
		SORT[value] = len(DB[value])
		for aleph in DB[value]:
			htm.write('<p><a style="color:#6DAE42;" target="_blank" href="https://aleph22.lib.cas.cz/F/?func=direct&doc_number=' +
				aleph + '&local_base=AV">' + aleph + '</a><font color="white">' + value + '</font></p>\n'
			)
			CNT_7+=1
	htm.write(HTML_BOTTOM)	
	htm.close()
	print("Done.")
	print("Generating 7 stat file..")
	for value in sorted(SORT, key=SORT.get, reverse=True):
		srt.write('<tr><td align="right"><font color="white">' + str(SORT[value]) + '</font></td>' +
			'<td><a style="color:#6DAE42;" target="_blank" href="https://vufind.ucl.cas.cz/Search/Results?lookfor=' + value +
			'&type=Author"></td>\n'
		)
	srt.write(SRT_BOTTOM)	
	srt.close()
	print("Done.")

	print("Writing global index ..")
	ind.write('<tr>' + '\n')
	ind.write('<td width="30" align="center"><font color="gold">' + TAG + '</font></td>' + '\n')
	ind.write('<td width="60" align="center"><a href="ucl/data/' + TAG + '.7.html" style="text-decoration:none;color:white">HTML</a></td>' + '\n')
	ind.write('<td width="40" align="center"><a href="ucl/raw/' + TAG + '.7.csv" style="text-decoration:none;color:white">CSV</a></td>' + '\n')
	ind.write('<td width="40" align="right">'+ str(CNT) + '</td>' + '\n')
	ind.write('<td width="60" align="center"><a href="ucl/data/' + TAG + '.7.stat.html" style="text-decoration:none;color:white">HTML</a></td>' + '\n')
	ind.write('<td width="60" align="center"><a href="ucl/data/' + TAG + '.html" style="text-decoration:none;color:white">HTML</a></td>' + '\n')
	ind.write('<td width="40" align="center"><a href="ucl/raw/' + TAG + '.csv" style="text-decoration:none;color:white">CSV</a></td>' + '\n')
	ind.write('<td width="40" align="right">' + str(CNT_7) + '</td>' + '\n')
	ind.write('<td width="60" align="center"><a href="ucl/data/' + TAG + '.stat.html" style="text-decoration:none;color:white">HTML</a></td>' + '\n')
	ind.write('</tr>' + '\n')

	# global counter
	ALL+=CNT
	ALL_7+=CNT_7

# EXIT

print("Writing index stat..")

ind.write('</table><br><br>')
ind.write('<table border="0" cellpadding="4px" style="border-collapse:collapse;"><tr>')
ind.write('<td align="right"><font color="gold">Podpole 7</font></td>')
ind.write('<td width="80" align="right"><font color="white">' + str(ALL_7) + '</font></td></tr>')
ind.write('<td width="80" align="right"> ' + str((ALL + ALL_7)/100*ALL_7) + '%</td>')
ind.write('<tr>')
ind.write('<td align="right"><font color="gold">Bez podpole 7</font></td>')
ind.write('<td width="80" align="right"><font color="white">' + str(ALL) + '</font></td>')
ind.write('<td width="80" align="right">' + str((ALL + ALL_7)/100*ALL) + '%</td>')
ind.write('</tr>')
ind.write('<tr><td align="right"><font color="gold">Celkem</font></td>')
ind.write('<td align="right"><font color="white">' + str(ALL + ALL_7) + '</font></td></tr>')
ind.write('</table>')
ind.write('<br><br>')
ind.write('<a href="/" title="Back"><font size="3" color="white">[Domů]</font></a>')
ind.write('<br><br></body></html>')

ind.close()

print("Exit.")

