#!/usr/bin/python3
#
# Owncloud WebDAV uploader
#

import easywebdav,smtplib,io,sys,os,re

from email.mime.text import MIMEText

# VAR -----------------------------------

DATA='/var/www/html/form/data'
ARCHIVE='/var/www/html/form/archive'

URL='https://xxx/index.php/apps/files/?dir=/UCL-DATA/CLANKY'
CSV='/public.php/webdav/clanky.csv'
PDF='/public.php/webdav/pdf'

SERVER='xxx'
TOKEN='xxx'
PASS='xxx'

MAIL_SENDER='xxx'
MAIL_TARGET='xxx'
MAIL_SERVER='xxx'
MAIL_SERVER_BACKUP='xxx'

buff = io.BytesIO()# CSV buffer
ID={}# File ID

# DEF -----------------------------------

def notify():
	html_header='Dobrý den,<br><br>'
	html_body='Nové články naleznete na adrese:<br><br><a target="_blank" href="' + URL + '">' + URL + '</a><br><br>ID článků:<br><br>'
	html_footer='<br>---------------------------<br><br>TATO ZPRÁVA BYLA VYGENEROVÁNA AUTOMATICKY, NEODPOVÍDEJTE NA NI.<br>'
	for i in ID: html_body+=(i + '<br>')
	msg = MIMEText(html_header + html_body + html_footer, 'html', 'utf-8')
	msg['Subject'] = 'Formulář - Články'
	msg['From'] = 'Vývoj <' + MAIL_SENDER + '>'
	msg['To'] = MAIL_TARGET
	try:
		s = smtplib.SMTP(MAIL_SERVER, timeout=10)
		s.sendmail(MAIL_SENDER, MAIL_TARGET, msg.as_string())
		s.quit()
	except:
		try:
			s = smtplib.SMTP(MAIL_SERVER_BACKUP, timeout=10)
			s.sendmail(MAIL_SENDER, MAIL_TARGET, msg.as_string())
			s.quit()
		except:
			print('Sendmail error.')

# MAIN -----------------------------------

webdav = easywebdav.connect(SERVER, username=TOKEN, password=PASS, protocol='https')

print('[.] Searching DATA.')
for fn in os.listdir(DATA):
	if re.match('^[a-z0-9]{13}\.csv$', fn):
		if fn[:13] not in ID:# PDF already
			ID[fn[:13]] = ''
	if re.match('^[a-z0-9]{13}_.+[pdf|PDF]$', fn):
			ID[fn[:13]] = fn

if ID:
	# Get CSV database
	print('[.] Downloading CSV.')
	try:
		webdav.download(CSV, buff)
	except Exception as e:
		print('[.] Failed to read CSV:')
		print(e.args[0])
		sys.exit(1)

	for rid in ID:
		# read CSV
		print('[.] ' + rid + ' Reading.')
		data=''
		try:
			with open(DATA + '/' + rid + '.csv', 'r') as f:
				data = f.read().strip()
		except:
			print('[.] ' + rid + ' Read failed.')
			continue

		if ID[rid]:
			# append PDF
			data += '|' +ID[rid] + '\n'
			# upload PDF
			print('[.] ' + rid + ' Uploading PDF.')
			try:
				webdav.upload(DATA + '/' + ID[rid], PDF + '/' + ID[rid])
			except Exception as e:
				print('[.] ' + rid + ' Upload PDF failed:')
				print(e.args[0])
				continue
			# archive PDF
			print('[.] ' + rid + ' Archiving PDF.')
			os.rename(DATA + '/' + ID[rid], ARCHIVE + '/' + ID[rid])
		else:
			data += '\n'
		# write CSV
		print('[.] ' + rid + ' Writing.')
		buff.write(data.encode('utf-8'))
		# archive CSV
		print('[.] ' + rid + ' Archiving.')
		os.rename(DATA + '/' + rid + '.csv', ARCHIVE + '/' + rid + '.csv')

	# update CSV database
	print('[.] Uploading CSV.')
	try:
		buff.seek(0)
		webdav.upload(buff, CSV)
	except Exception as e:
		print('[.] Upload CSV failed.')
		print(e.args[0])
		sys.exit(1)

	# Notify
	notify()

# EXIT
sys.exit(0)

