#!/usr/bin/python3
#
# WebDAV upload client
#

import easywebdav,argparse,getpass,sys,os,re

URL='data.ucl.cas.cz'
BASE='/remote.php/webdav/UCL-DATA/'

# ARGS

parser = argparse.ArgumentParser(description="WebDAV client.")

required = parser.add_argument_group()
required.add_argument('--source', help='Source file or directory.')
required.add_argument('--target', help='Traget directory.')
args = parser.parse_args()

if not args.source: parser.error('argument --source is required.')
if not args.target: parser.error('argument --target is required.')

if not ( os.path.isfile(args.source) or os.path.isdir(args.source) ):
	print("Bad source.")
	sys.exit(1)

# USER/PASS

try:
	user = input('User: ')
except:
	print("Bad user.")
	sys.exit(1)
try:
	passw = getpass.getpass()
except:
	print("Bad password.")
	sys.exit(1)

# WEBDAV

webdav = easywebdav.connect(URL, username=user,password=passw, protocol='https')

if os.path.isfile(args.source):
	try:
		print(args.source + ' -> ' + BASE + args.target)	
		webdav.upload(args.source, BASE  + args.target)	
	except Exception as e:
		print(e.args[0])

if os.path.isdir(args.source):

	cwd = os.getcwd()
	os.chdir(args.source)

	try:# base dir
		webdav.mkdirs(BASE + '/' + args.target)
	except Exception as e:
		print(e.args[0])

	# dir structure
	for root,dirs,files in os.walk(args.source):
		for name in dirs:
			try:# dir structure	
				print(BASE + args.target.strip('/') + '/' + os.path.relpath(os.path.join(root,name),args.source))
				webdav.mkdirs(BASE + args.target.strip('/') + '/' + os.path.relpath(os.path.join(root,name),args.source))
			except Exception as e:
				print(e.args[0])
	# files
	for root,dirs,files in os.walk(args.source):
		for name in files:
			try:# files
				print(os.path.join(root,name) + ' -> ' + BASE + args.target.strip('/') + '/' + os.path.relpath(os.path.join(root,name),args.source))
				webdav.upload(os.path.join(root,name), BASE + args.target.strip('/') + '/' + os.path.relpath(os.path.join(root,name),args.source))
			except Exception as e:
				print(e.args[0])

	os.chdir(cwd)

# EXIT

sys.exit(0)

