<?php if (isset($this->showCheckboxes) && $this->showCheckboxes): ?>
  <nav class="bulkActionButtons">
    <div class="bulk-checkbox">
      <input type="checkbox" class="checkbox-select-all" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/>
      <label for="<?=$this->idPrefix?>addFormCheckboxSelectAll">
        <?=$this->transEsc('select_page')?>
        &#124; <?=$this->transEsc('with_selected')?>:
      </label>
    </div>
    <ul class="action-toolbar">
      <?php if (isset($this->showBulkOptions) && $this->showBulkOptions): ?>
        <li><button id="ribbon-email" class="toolbar-btn btn-type-email" type="submit" name="email" value="1" title="<?=$this->transEscAttr('bookbag_email_selected')?>"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Email')?></button></li>
        <li><a target="_blank" href="<?=$this->url('export')?>/<?=$this->layout()->userLang?>/<?=$this->results->getUrlQuery()?>"><button id="ribbon-export" class="toolbar-btn btn-type-export" type="button" name="export" value="1" title="<?=$this->transEscAttr('bookbag_export_selected')?>"><?=$this->transEsc('Export')?></button></a></li>
        <li><button id="ribbon-print" class="toolbar-btn btn-type-print" type="submit" name="print" value="1" title="<?=$this->transEscAttr('bookbag_print_selected')?>"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Print')?></button></li>
        <li><a target="_blank" href="<?=$this->url('sam')?>/<?=$this->layout()->userLang?>/<?=$this->results->getUrlQuery()?>"><button id="ribbon-charts" class="toolbar-btn btn-type-chart" type="button" name="chart" value="1" title="<?=$this->transEscAttr('Show Charts')?>"><?=$this->transEsc('Charts')?></button></a></li>
        <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
          <li><button id="ribbon-save" class="toolbar-btn btn-type-save" type="submit" name="saveCart" value="1" title="<?=$this->transEscAttr('bookbag_save_selected')?>"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Save')?></button></li>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (isset($this->showCartControls) && $this->showCartControls): ?>
        <li><button id="<?=$this->idPrefix?>updateCart" type="submit" class="toolbar-btn btn-type-add" name="add" value="1"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Add to Book Bag')?></button></li>
      <?php endif; ?>
    </ul>
  </nav>
<?php endif; ?>
